#!/bin/sh
# release-manifest.sh -- the release artifacts' integrity manifest.
#
# From the generated amalgams (build/boot/*.x, discovered -- never a
# hand list), emits into build/release/:
#
#   SHASUMS          coreutils format (HEX  name), so a consumer can run
#                    `sha256sum -c SHASUMS` beside downloaded files
#   pin.release.xon  the machine-readable manifest -- xon (read, never
#                    evaluated), the same closed-vocabulary family as
#                    pin.xon / pin.lock.xon:
#                      (release "TAG")
#                      (isa "sha256:HEX")     the C-surface fingerprint:
#                                             the digest of tools/isa.x,
#                                             the ratcheted ISA manifest
#                                             these amalgams were built
#                                             against (make check-isa
#                                             holds manifest == binary)
#                      (file "x.x" "sha256:HEX") one per amalgam
#
# Self-checking, the install-recipe way: a missing amalgam dir, an
# unhashable file, or a malformed digest fails the run -- there is no
# partial manifest.
#
# Usage: sh tools/release-manifest.sh <tag>
set -u

cd "$(dirname "$0")/.." || exit 1

TAG="${1:-}"
[ -n "$TAG" ] || { echo "release-manifest: usage: release-manifest.sh <tag>" >&2; exit 1; }
[ -d build/boot ] || { echo "release-manifest: no build/boot -- run 'make boot' first" >&2; exit 1; }

# Portable digest: coreutils on Linux, shasum on macOS.
if command -v sha256sum >/dev/null 2>&1; then
  _digest() { sha256sum "$1" | awk '{print $1}'; }
elif command -v shasum >/dev/null 2>&1; then
  _digest() { shasum -a 256 "$1" | awk '{print $1}'; }
else
  echo "release-manifest: no sha256sum or shasum on PATH" >&2; exit 1
fi

check_hex() { # 64 lowercase hex chars, or die
  case "$1" in
    *[!0-9a-f]*) echo "release-manifest: malformed digest for $2" >&2; exit 1 ;;
  esac
  [ "${#1}" -eq 64 ] || { echo "release-manifest: short digest for $2" >&2; exit 1; }
}

# Build under .tmp names, move into place only on full success -- a
# failed run must not leave a partial manifest behind.
mkdir -p build/release
: > build/release/SHASUMS.tmp
{
  printf '; pin.release.xon -- generated by tools/release-manifest.sh; do not edit\n'
  printf '(release "%s")\n' "$TAG"
  isa=$(_digest tools/isa.x)
  check_hex "$isa" tools/isa.x
  printf '(isa "sha256:%s")\n' "$isa"
  n=0
  for f in build/boot/*.x; do
    [ -e "$f" ] || { echo "release-manifest: no amalgams in build/boot" >&2; exit 1; }
    d=$(_digest "$f")
    check_hex "$d" "$f"
    printf '%s  %s\n' "$d" "$(basename "$f")" >> build/release/SHASUMS.tmp
    printf '(file "%s" "sha256:%s")\n' "$(basename "$f")" "$d"
    n=$((n + 1))
  done
  [ "$n" -gt 0 ] || { echo "release-manifest: zero amalgams hashed" >&2; exit 1; }
} > build/release/pin.release.xon.tmp || exit 1

mv build/release/SHASUMS.tmp build/release/SHASUMS
mv build/release/pin.release.xon.tmp build/release/pin.release.xon
echo "release-manifest: $(grep -c '^(file ' build/release/pin.release.xon) amalgams + isa fingerprint for $TAG"
