; pin.x -- arm a project's overlay import roots from its pin.xon manifest
;
; Tier 2 of the pinning design (GH #115): a project vendors the modules it
; pins into a tree (e.g. deps/) and declares that tree in pin.xon; import
; then resolves pinned names against the overlay before the platform
; library.  The shell wrapper probes for pin.xon (walking up from the
; program's directory; the cwd for a REPL; --no-pin skips) and, when
; found, ANNOUNCES it as data -- (def %pin-file "<abs path>") ahead of
; the boot entry, (import x/tool/pin) after it -- so arming lands
; post-boot, before the first user form.
;
; The manifest is xon -- x object notation: a sequence of x-lang data
; forms read with the ordinary reader and NEVER evaluated.  This module
; interprets a CLOSED vocabulary over those forms; anything else is a
; loud error.  A hostile manifest can therefore only do what pinning
; does: redirect import resolution into its own project's files.
;
; Vocabulary:
;   (root "DIR")   overlay root; a relative DIR resolves against the
;                  manifest's own directory.  First root listed wins.
;   (boot "FILE")  boot entry (a pinned amalgam) -- consumed by the
;                  SHELL WRAPPER, which must choose the entry before
;                  the pipe exists; this loader only checks the shape.
;
; The pre-seeded boot set is unpinnable by construction: boot modules
; are already registered in %module-loaded-cell, so an import of them
; no-ops before any root is consulted.  Pinning the platform itself is
; tier 1 (amalgam pinning), not this file.

; Boot-floor snapshot -- MUST stay this module's first form, before its
; own imports below add to the registry.  At arming time (the wrapper's
; import lands before any user form) this is exactly the boot pre-seed:
; the unpinnable core.  The vendor walk skips these names, which is why
; vendor sessions are run fresh with this module imported FIRST.
(def %pin-floor (first %module-loaded-cell))

(import x/sys/file)
; Eager on purpose, both: sha256 (and posix, which fetch's curl runner
; rides) must resolve PLATFORM-side, before any overlay root is armed
; below -- a lazy import inside verify/fetch could be shadowed by the
; very overlay it is checking (the pin-the-pinner hole, closed the same
; way the wrapper closes it for this module itself).
(import x/sys/posix)
(import x/codec/sha256)
(import x/sys/proc)
(import x/codec/xon)
(import x/type/path)

; --- The Pin class: the whole tool, one namespace ---------------------
; Every helper is a %-prefixed STATIC on the class -- private by
; convention, namespaced in fact.  Sibling calls go through (Pin %name
; ...); the class name is the module's one public global, so nothing
; else leaks into the session (tools/check/percent-globals.sh holds the
; line).  Two composition rules learned the hard way:
;   - RECURSION IS LOOP-LOCAL: a self-recursive helper binds its loop as
;     a local fn and dispatches ONCE per entry.  Static dispatch walks
;     the class's ~110-entry table per call, and a dispatch per tree
;     node timed out the ASan CI leg outright.
;   - The single top-level exception is %pin-floor above: the boot-floor
;     snapshot must be taken BEFORE this file's imports run, and the
;     class does not exist yet at that point.
(def-class Pin ()
  (static
    ; --- The manifest as the TOOL reads it -------------------------------
    ; The loader above turns (root ...) into armed import paths and discards
    ; the rest; the verbs need the VALUES, so read them back by head.  Path
    ; arguments resolve against the manifest's directory, exactly as (root
    ; ...) does, so a manifest means the same thing from any cwd.
    (%pin-manifest-name "pin.xon")
    ; Walk state (reset per closure call; the tool is a single-session
    ; utility, mirroring boot-order.x's cell style).
    (%pin-visited-cell (pair () ()))
    (%pin-out-cell (pair () ()))
    ; --- The lockfile (GH #115 phase 4): the overlay's integrity record ---
    ; <dest>/pin.lock.xon, generated by vendor; xon like the manifest, with
    ; a closed vocabulary of (file "REL" "sha256:HEX") forms.  verify
    ; recomputes every digest AND walks the tree, so a modified file, a
    ; missing file, or an UNLISTED file (a rogue shadow ready to win root
    ; precedence) is a loud error -- the overlay must be exactly the lock.
    ;
    ; PROVENANCE (GH #147): one overlay legitimately holds several vendors --
    ; the tutorial's "repeated vendors into one overlay merge cleanly" -- so
    ; the file list alone cannot say which vendor put a file there.  Without
    ; that, re-vendoring a seed whose upstream DROPPED a dependency left the
    ; orphan in the tree AND in the lock, still shadowing the platform, with
    ; verify calling the pair clean because both had gone stale together.
    ; So each vendor also records what it claimed:
    ;   (seed "NAME" "rel" ...)   NAME = a module name, or "project:DIR"
    ; Re-vendoring a seed replaces that seed's claim; a rel no other seed
    ; claims leaves the lock and is reported.  Entries predating this record
    ; are unattributed and kept as-is, so an old overlay keeps verifying.
    (%pin-lock-name "pin.lock.xon")
    (%pin-platform-heads (list 'release 'isa 'boot))
    (%pin-lock-header "; pin.lock.xon -- generated; do not edit\n")
    ; The canonical release home; a trailing optional on fetch overrides it
    ; (a mirror, or file:// in the smoke).
    (%pin-release-base "https://github.com/jonruttan/x-lang/releases/download")
    (%pin-release-name "pin.release.xon")
    (method %pin-bad (self what)
      (error (Str8 append "pin: " what)))
    ; Read manifest text as forms, never evaluating.  The end-of-buffer
    ; termination workaround lives in the shared door (Xon parse, #230).
    (method %pin-forms (self text)
      (Xon parse text))
    ; One (root "DIR") form -> the resolved root string.  %path-join is
    ; module.x's boot-level path helper (boot-adjacent accessors rule).
    (method %pin-root (self form dir)
      (match
            ((not (pair? (rest form))) (Pin %pin-bad "root needs one string argument"))
            ((not (null? (rest (rest form)))) (Pin %pin-bad "root takes exactly one argument"))
            ((not (str? (first (rest form)))) (Pin %pin-bad "root argument must be a string"))
            ((Path absolute? (first (rest form))) (first (rest form)))
            (#t (%path-join dir (first (rest form))))))
    ; One (boot "FILE") form -> () -- wrapper-consumed (GH #139): the entry
    ; must be chosen before the pipe exists, so by the time this loader
    ; runs the pinned boot is already the running boot.  Shape-checked here
    ; so a malformed form stays a loud error under the closed vocabulary.
    (method %pin-boot (self form)
      (match
            ((not (pair? (rest form))) (Pin %pin-bad "boot needs one string argument"))
            ((not (null? (rest (rest form)))) (Pin %pin-bad "boot takes exactly one argument"))
            ((not (str? (first (rest form)))) (Pin %pin-bad "boot argument must be a string"))
            (#t ())))
    ; One (src "DIR") form -> () -- tool-side, like boot.  It names where the
    ; PROJECT's own sources live, which is what lets sync and check derive the
    ; pin from the code that exists rather than a list written in advance: the
    ; imports ARE the dependency declaration.  Inert at load time; the loader
    ; arms roots, and a source directory is not a root.
    (method %pin-src (self form)
      (match
            ((not (pair? (rest form))) (Pin %pin-bad "src needs one string argument"))
            ((not (null? (rest (rest form)))) (Pin %pin-bad "src takes exactly one argument"))
            ((not (str? (first (rest form)))) (Pin %pin-bad "src argument must be a string"))
            (#t ())))
    ; Manifest forms + manifest dir -> resolved roots, manifest order.
    ; Closed vocabulary: an unknown head is an error, not a skip.
    (method %pin-interpret (self forms dir)
      ; The vocabulary is the table; boot/src validate and yield nil, so
      ; the walk's result is exactly the resolved roots in manifest order.
      (Xon walk
        (list (pair (lit root) (fn (_ f) (Pin %pin-root f dir)))
              (pair (lit boot) (fn (_ f) (Pin %pin-boot f)))
              (pair (lit src)  (fn (_ f) (Pin %pin-src f))))
        (fn (_ f)
          (match
            ((not (pair? f)) (Pin %pin-bad "form is not a list"))
            (#t (Pin %pin-bad "unknown form"))))
        forms))
    (method %pin-manifest-arg (self head forms dir)
      (let ((hit (%find (fn (_ f) (if (pair? f) (eq? (first f) head) #f)) forms)))
            (match
              ((null? hit) ())
              ((not (pair? (rest hit))) ())
              ((Path absolute? (first (rest hit))) (first (rest hit)))
              (#t (%path-join dir (first (rest hit)))))))
    ; The same lookup WITHOUT resolution -- the manifest's own spelling.
    ; What the lock records has to be portable: "maze", not the absolute
    ; path this particular machine resolved it to.
    (method %pin-manifest-raw (self head forms)
      (let ((hit (%find (fn (_ f) (if (pair? f) (eq? (first f) head) #f)) forms)))
            (match
              ((null? hit) ())
              ((not (pair? (rest hit))) ())
              (#t (first (rest hit))))))
    (method %pin-manifest-forms (self dir)
      (let ((p (%path-join dir (Pin %pin-manifest-name))))
            (match
              ((not (File exists? p))
                ; The one error a NEWCOMER hits first: name the way out, not
                ; just the absence.
                (Pin %pin-bad (Str8 append "no manifest: "
                            (Str8 append p " -- (Pin init) writes a starter"))))
              (#t (Pin %pin-forms (File read-all p))))))
    ; Arm: prepend each root via import-path!, last-listed first, so the
    ; manifest's FIRST root ends up with the highest precedence.  A missing
    ; root directory is a broken project -- fail loudly, never silently
    ; unarmed (File exists? is access(2), so it accepts directories).
    (method %pin-arm! (self roots)
      (def %rec (fn (self roots)
        (match
              ((null? roots) ())
              (#t
                (do (self (rest roots))
                    (match
                      ((File exists? (first roots)) ())
                      (#t (Pin %pin-bad (Str8 append "root does not exist: " (first roots)))))
                    (import-path! (first roots))
                    ())))))
      (%rec roots))
    ; Lexical normalization is (Path norm); the OVERLAY POLICY -- a rel
    ; that climbs out of the overlay is an error -- stays here, read off
    ; the leading ".." that Path norm preserves for exactly this judgment.
    (method %pin-path-norm (self p)
      (let ((r (Path norm p)))
            (match
              ((if (str=? r "..") #t (Str8 starts? "../" r))
                (Pin %pin-bad (Str8 append "include path climbs out of the overlay: " p)))
              (#t r))))
    (method %pin-include-head? (self h)
      (or (eq? h 'include) (eq? h 'include-once) (eq? h 'require-once)))
    (method %pin-push! (self cell v)
      (%set-first! cell (pair v (first cell))))
    ; A ./ sibling: same tail joined under both the overlay offset and the
    ; source dir; scanned like any file (it may import).
    (method %pin-take-rel (self dirs tail)
      ; The overlay rel is normalised (it keys the lockfile and targets the
          ; copy); the SOURCE path keeps its ".." -- it is only ever opened, and
          ; the OS resolves it against the real tree.
          (let ((rel (Pin %pin-path-norm (%path-join (first dirs) tail))))
            (match
              ((Pin %pin-out-has? rel) ())
              (#t
                (do (Pin %pin-push! (Pin %pin-out-cell) (pair rel (%path-join (rest dirs) tail)))
                    (Pin %pin-walk-file rel (%path-join (rest dirs) tail)))))))
    (method %pin-out-has? (self rel)
      (not (null? (%assoc-str rel (first (Pin %pin-out-cell))))))
    ; Closure of NAME: (root-relative . source) pairs, discovery order.  A
    ; floor seed is the caller's error to reject; here it just yields ().
    (method %pin-closure-of (self name)
      (do (%set-first! (Pin %pin-visited-cell) ())
              (%set-first! (Pin %pin-out-cell) ())
              (Pin %pin-take-module name)
              (%reverse (first (Pin %pin-out-cell)))))
    ; mkdir -p: ensure every prefix of dir exists.  EEXIST races are settled
    ; by the guard; a real failure surfaces at the write-all that follows.
    (method %pin-mkdirs (self dir)
      (def %rec (fn (self dir)
        (match
              ((str=? dir ".") ())
              ((str=? dir "") ())
              ((File exists? dir) ())
              (#t
                (do (self (%path-dir dir))
                    (guard (_ ()) (File mkdir dir))
                    ())))))
      (%rec dir))
    (method %pin-copy! (self dest entry)
      (let ((target (%path-join dest (first entry))))
            (do (Pin %pin-mkdirs (%path-dir target))
                (File write-all target (File read-all (rest entry)))
                ())))
    (method %pin-rels (self entries)
      (def %go
            (fn (self lst)
              (match
                ((null? lst) ())
                (#t (pair (first (first lst)) (self (rest lst)))))))
          (%go entries))
    (method %pin-copy-all! (self dest lst)
      (def %rec (fn (self dest lst)
        (match
              ((null? lst) ())
              (#t (do (Pin %pin-copy! dest (first lst))
                      (self dest (rest lst)))))))
      (%rec dest lst))
    (method %pin-digest (self path)
      (Str8 append "sha256:" (Sha256 hex (File read-all path))))
    ; The closed vocabulary is (file ...) | (seed ...); each reader takes the
    ; forms it owns and ignores -- never rejects -- the other's.
    (method %pin-lock-parse (self forms)
      ; seed and the platform half -- (release ...) (isa ...) (boot ...),
      ; written by the boot verb -- pass through untaken: a reader takes
      ; the forms it owns and ignores the other's, so the vocabulary
      ; stays closed without either half rejecting the other.
      (def %skip (fn (_ f) ()))
      (Xon walk
        (pair (pair (lit file)
                (fn (_ f)
                  (match
                    ((not (str? (first (rest f))))
                      (Pin %pin-bad "lockfile entry needs a path string"))
                    ((not (str? (first (rest (rest f)))))
                      (Pin %pin-bad "lockfile entry needs a digest string"))
                    (#t (pair (first (rest f)) (first (rest (rest f))))))))
          (pair (pair (lit seed) %skip)
                (%map (fn (_ h) (pair h %skip)) (Pin %pin-platform-heads))))
        (fn (_ f)
          (match
            ((not (pair? f)) (Pin %pin-bad "lockfile form is not a list"))
            (#t (Pin %pin-bad "unknown lockfile form"))))
        forms))
    ; (seed "NAME" "rel" ...) -> (NAME . (rel ...)) pairs, file order.
    (method %pin-lock-parse-seeds (self forms)
      (def %rels
            (fn (self lst)
              (match
                ((null? lst) ())
                ((not (str? (first lst))) (Pin %pin-bad "seed entry needs path strings"))
                (#t (pair (first lst) (self (rest lst)))))))
          (Xon walk
            (list (pair (lit seed)
                    (fn (_ f)
                      (match
                        ((not (str? (first (rest f))))
                          (Pin %pin-bad "seed entry needs a name string"))
                        (#t (pair (first (rest f)) (%rels (rest (rest f)))))))))
            (fn (_ f)
              (match
                ((not (pair? f)) (Pin %pin-bad "lockfile form is not a list"))
                (#t ())))
            forms))
    ; Final path segment.  Used for the lock's name, and by the boot verb to
    ; take its amalgam name from the manifest's (boot "boot/he.x") -- so the
    ; file name is data the project already stated, with no dialect symbol to
    ; repeat at the call site.
    ; The lock sits BESIDE the overlay root and is NAMED FOR IT -- deps/ is
    ; locked by deps.lock.xon.  Two reasons, and the second is the one that
    ; bites: an integrity record kept inside the tree it describes reads as
    ; part of the payload (vendor writes that tree, verify may condemn it),
    ; and a fixed name in the parent would make two overlays sharing a parent
    ; share one lock and silently clobber each other -- which is exactly what
    ; the spec suite does, vendoring build/pin-spec/prov and .../partial.
    (method %pin-lock-path (self dest)
      (%path-join (%path-dir dest)
                      (Str8 append (Path basename dest) ".lock.xon")))
    (method %pin-lock-forms (self dest)
      (let ((p (Pin %pin-lock-path dest)))
            (match
              ((File exists? p) (Pin %pin-forms (File read-all p)))
              (#t ()))))
    ; The platform half of the lock -- (release ...) (isa ...) (boot ...),
    ; written by `boot`.  relock rewrites the whole file from the overlay's
    ; forms, so these must survive a sync that knows nothing about them.
    (method %pin-str->sym (self s) ((prim-ref (lit str) (lit ->sym)) s))
    (method %pin-platform-forms (self forms)
      (%filter (fn (_ f) (if (pair? f) (%memq? (first f) (Pin %pin-platform-heads)) #f))
               forms))
    (method %pin-lock-read (self dest)
      (Pin %pin-lock-parse (Pin %pin-lock-forms dest)))
    (method %pin-lock-read-seeds (self dest)
      (Pin %pin-lock-parse-seeds (Pin %pin-lock-forms dest)))
    ; No header here: both writers emit (Pin %pin-lock-header) first, so that a
    ; lock carrying platform lines does not end up with its own banner
    ; stranded in the middle of the file.
    (method %pin-lock-render (self entries)
      (Xon emit (%map (fn (_ e) (list (lit file) (first e) (rest e))) entries)))
    (method %pin-seed-render (self seeds)
      (Xon emit (%map (fn (_ st) (pair (lit seed) (pair (first st) (rest st)))) seeds)))
    ; Order-preserving upsert of one seed's claim.
    (method %pin-seed-put (self seeds name rels)
      (def %rec (fn (self seeds name rels)
        (match
              ((null? seeds) (pair (pair name rels) ()))
              ((str=? (first (first seeds)) name) (pair (pair name rels) (rest seeds)))
              (#t (pair (first seeds) (self (rest seeds) name rels))))))
      (%rec seeds name rels))
    ; acc ++ (lst minus what acc holds)
    (method %pin-append-new (self acc lst)
      (def %rec (fn (self acc lst)
        (match
              ((null? lst) acc)
              ((%member-str? (first lst) acc) (self acc (rest lst)))
              (#t (self (Pin %pin-concat acc (list (first lst))) (rest lst))))))
      (%rec acc lst))
    ; every rel any seed claims
    (method %pin-seed-claims (self seeds acc)
      (def %rec (fn (self seeds acc)
        (match
              ((null? seeds) acc)
              (#t (self (rest seeds) (Pin %pin-append-new acc (rest (first seeds))))))))
      (%rec seeds acc))
    ; rels absent from lst
    (method %pin-not-in (self rels lst)
      (def %rec (fn (self rels lst)
        (match
              ((null? rels) ())
              ((%member-str? (first rels) lst) (self (rest rels) lst))
              (#t (pair (first rels) (self (rest rels) lst))))))
      (%rec rels lst))
    ; Rewrite the lock with SEED now claiming RELS.  The file list becomes
    ; every rel still claimed, plus entries no seed ever claimed (written
    ; before provenance existed -- kept, never silently dropped).  Returns
    ; the rels that left the lock: files this seed used to pull in and no
    ; longer does, which now shadow the platform for nothing.
    ; rels -> (rel . digest), digests fresh
    (method %pin-lock-entries (self dest rels)
      (def %rec (fn (self dest rels)
        (match
              ((null? rels) ())
              (#t (pair (pair (first rels) (Pin %pin-digest (%path-join dest (first rels))))
                        (self dest (rest rels)))))))
      (%rec dest rels))
    (method %pin-lock-relock! (self dest seed rels)
      (let ((old-rels (Pin %pin-rels (Pin %pin-lock-read dest)))
                (was-seeds (Pin %pin-lock-read-seeds dest)))
            (let ((seeds (Pin %pin-seed-put was-seeds seed rels))
                  ; Unattributed: in the file list, claimed by no seed -- an
                  ; overlay locked before provenance existed.  Keep them.
                  (loose (Pin %pin-not-in old-rels (Pin %pin-seed-claims was-seeds ()))))
              (let ((live (Pin %pin-append-new (Pin %pin-seed-claims seeds ()) loose)))
                (do
                  ; The platform lines ride through untouched: a sync re-derives
                  ; the overlay from source and must not silently unpin the
                  ; language underneath it.
                  (File write-all (Pin %pin-lock-path dest)
                    (Str8 append (Pin %pin-lock-header)
                      (Str8 append (Xon emit (Pin %pin-platform-forms (Pin %pin-lock-forms dest)))
                        (Str8 append (Pin %pin-lock-render (Pin %pin-lock-entries dest live))
                                     (Pin %pin-seed-render seeds)))))
                  (Pin %pin-not-in old-rels live))))))
    ; A dropped file is not deleted -- vendor writes into a tree the project
    ; owns, and removing files there is the user's call.  It is named, and
    ; verify will flag it as unlisted until it goes.
    (method %pin-report-dropped (self dest dropped)
      (match
            ((null? dropped) ())
            (#t (do (display $"pin: {(Pin %pin-length dropped)} file(s) no longer in the closure, still in {dest} (delete them; verify flags them as unlisted):\n{(Pin %pin-join-lines dropped)}")
                    ()))))
    (method %pin-tree-files (self root)
      (Pin %pin-tf-walk root "" ()))
    (method %pin-verify-fails (self dest lock)
      (def %entry-fails
            (fn (self lst acc)
              (match
                ((null? lst) acc)
                ((not (File exists? (%path-join dest (first (first lst)))))
                  (self (rest lst) (pair (Str8 append "missing: " (first (first lst))) acc)))
                ((str=? (Pin %pin-digest (%path-join dest (first (first lst)))) (rest (first lst)))
                  (self (rest lst) acc))
                (#t (self (rest lst) (pair (Str8 append "modified: " (first (first lst))) acc))))))
          (def %lock-has?
            (fn (_ rel lst) (not (null? (%assoc-str rel lst)))))
          ; Dotfiles are outside the module layout, so outside the threat: an
          ; unlisted file matters because a module RESOLVES to it, and no module
          ; name resolves to a dotfile.  Skipping them is what lets a
          ; declared-but-empty overlay survive both git (deps/.gitkeep) and
          ; verify at once (GH #217) -- and keeps .DS_Store from poisoning a
          ; mac's overlay.
          (def %dot-base?
            (fn (_ rel)
              (Str8 starts? "." (Path basename rel))))
          (def %tree-fails
            (fn (self files acc)
              (match
                ((null? files) acc)
                ((str=? (first files) (Pin %pin-lock-name)) (self (rest files) acc))
                ((%dot-base? (first files)) (self (rest files) acc))
                ((%lock-has? (first files) lock) (self (rest files) acc))
                (#t (self (rest files) (pair (Str8 append "unlisted: " (first files)) acc))))))
          (%tree-fails (Pin %pin-tree-files dest) (%entry-fails lock ())))
    (method %pin-join-lines (self lst)
      (def %rec (fn (self lst)
        (match
              ((null? lst) "")
              (#t (Str8 append (first lst) (Str8 append "\n" (self (rest lst))))))))
      (%rec lst))
    (method %pin-length (self lst)
      (def %rec (fn (self lst)
        (match
              ((null? lst) 0)
              (#t (+ 1 (self (rest lst)))))))
      (%rec lst))
    ; A URL, not a filesystem path: (Path join) would be wrong here (its
    ; seam collapse would eat the scheme's "//").
    (method %pin-url (self base tag file)
      (Str8 append base (Str8 append "/" (Str8 append tag (Str8 append "/" file)))))
    ; Download via curl through Proc run! (#226): 127 = curl absent,
    ; anything else nonzero = the download failed.
    (method %pin-download! (self url target)
      ; -f: HTTP errors fail the exit status; -L: release downloads
          ; redirect; -sS: quiet but errors still print
          (let ((status (Proc run! (list "curl" "-fsSL" "-o" target url))))
            (match
              ((= status 0) ())
              ((= status 127)
                (Pin %pin-bad (Str8 append "curl not found -- download manually and re-run against the files:\n  " url)))
              (#t (Pin %pin-bad (Str8 append "download failed: " url))))))
    ; pin.release.xon -> ((release . TAG) (isa . DIGEST) (files . ALIST)),
    ; closed vocabulary: release | isa | (file NAME DIGEST).
    (method %pin-release-parse (self forms)
      (def %go
            (fn (self forms tag isa files)
              (match
                ((null? forms)
                  (match
                    ((null? tag) (Pin %pin-bad "release manifest has no (release ...)"))
                    (#t (list (pair 'release tag) (pair 'isa isa) (pair 'files files)))))
                ((not (pair? (first forms))) (Pin %pin-bad "release-manifest form is not a list"))
                ((eq? (first (first forms)) 'release)
                  (match
                    ((str? (first (rest (first forms))))
                      (self (rest forms) (first (rest (first forms))) isa files))
                    (#t (Pin %pin-bad "release needs a tag string"))))
                ((eq? (first (first forms)) 'isa)
                  (match
                    ((str? (first (rest (first forms))))
                      (self (rest forms) tag (first (rest (first forms))) files))
                    (#t (Pin %pin-bad "isa needs a digest string"))))
                ((eq? (first (first forms)) 'file)
                  (match
                    ((not (str? (first (rest (first forms)))))
                      (Pin %pin-bad "release file needs a name string"))
                    ((not (str? (first (rest (rest (first forms))))))
                      (Pin %pin-bad "release file needs a digest string"))
                    (#t (self (rest forms) tag isa
                          (pair (pair (first (rest (first forms)))
                                      (first (rest (rest (first forms)))))
                                files)))))
                (#t (Pin %pin-bad "unknown release-manifest form")))))
          (%go forms () () ()))
    (method %pin-release-file (self name files)
      (let ((hit (%assoc-str name files)))
            (match
              ((null? hit) (Pin %pin-bad (Str8 append "not in the release manifest: " name)))
              (#t (rest hit)))))
    ; two lists, a ++ b
    (method %pin-concat (self a b)
      (def %rec (fn (self a b)
        (match
              ((null? a) b)
              (#t (pair (first a) (self (rest a) b))))))
      (%rec a b))
    ; path -> 'file | 'dir | ... (File stat's kind)
    (method %pin-kind (self path)
      (%assoc-get 'kind (File stat path)))
    ; does name end in ".x"?
    (method %pin-ends-x? (self name)
      (Str8 ends? ".x" name))
    ; dir -> every *.x path under dir, recursive
    (method %pin-x-files (self dir)
      (def %rec (fn (self dir)
        (def %go
              (fn (go names)
                (match
                  ((null? names) ())
                  (#t
                    (let ((p (%path-join dir (first names))))
                      (Pin %pin-concat
                        (match
                          ((eq? (Pin %pin-kind p) 'dir) (self p))
                          ((Pin %pin-ends-x? (first names)) (list p))
                          (#t ()))
                        (go (rest names))))))))
            (%go (File list-dir dir))))
      (%rec dir))
    (method %pin-scan-project-files (self paths)
      (def %rec (fn (self paths)
        (match
              ((null? paths) ())
              (#t (do (Pin %pin-scan-project-list (Pin %pin-forms (File read-all (first paths))))
                      (self (rest paths)))))))
      (%rec paths))
    ; srcdir -> (rel . src) entries: the union closure of every import the
    ; project's sources reference, discovery order (dedup via the walk's
    ; visited set).
    (method %pin-project-closure (self srcdir)
      (do (%set-first! (Pin %pin-visited-cell) ())
              (%set-first! (Pin %pin-out-cell) ())
              (Pin %pin-scan-project-files (Pin %pin-x-files srcdir))
              (%reverse (first (Pin %pin-out-cell)))))
    ; Required rels absent from dest: each such import silently resolves to
    ; the platform, not the overlay (a half-pin).
    (method %pin-audit-missing (self dest rels)
      (def %rec (fn (self dest rels)
        (match
              ((null? rels) ())
              ((File exists? (%path-join dest (first rels))) (self dest (rest rels)))
              (#t (pair (first rels) (self dest (rest rels)))))))
      (%rec dest rels))
    ; Vendor a whole source tree's union closure into dest.  Shared by the
    ; vendor-project method (explicit paths) and by sync (paths from the
    ; manifest) so both do exactly the same thing -- one mechanism, two doors.
    ; label is what the lock RECORDS as the seed; srcdir is what gets
    ; scanned.  They differ for sync, which scans a path resolved against
    ; the manifest's directory but must record the manifest's own spelling:
    ; a resolved path can be absolute, and an absolute path in a committed
    ; lockfile is both meaningless on another machine and a quiet leak of
    ; wherever the author happened to keep the project.
    (method %pin-vendor-project! (self dest srcdir label)
      (let ((entries (Pin %pin-project-closure srcdir)))
            (let ((rels (Pin %pin-rels entries)))
              ; A project whose imports are all boot floor yields an empty
              ; closure, and dest must still exist for the lockfile.  The seed
              ; is the SOURCE DIR, not a module: the claim is "what this
              ; project's sources need", replaced wholesale on each scan.
              (do (Pin %pin-mkdirs dest)
                  (Pin %pin-copy-all! dest entries)
                  (Pin %pin-report-dropped dest
                    (Pin %pin-lock-relock! dest (Str8 append "project:" label) rels))
                  rels))))
    ; Drop a trailing ".x": the manifest names a FILE, the release names an
    ; ENTRY, and this is the one place the two spellings meet.
    (method %pin-entry-of (self file)
      (Pin %pin-str->sym (Path strip-ext file)))
    ; Replace the lock's platform lines, keeping the overlay's untouched.
    ; The inverse of the passthrough in relock: `boot` owns these three forms,
    ; `sync` owns the rest, and neither may clobber the other's half.
    (method %pin-lock-set-platform! (self dest forms)
      (let ((old (Pin %pin-lock-forms dest)))
            (File write-all (Pin %pin-lock-path dest)
              (Str8 append (Pin %pin-lock-header)
                (Str8 append (Xon emit forms)
                             (Pin %pin-nonplatform-render old))))))
    (method %pin-nonplatform-render (self forms)
      (Xon emit
        (%filter (fn (_ f)
                   (if (pair? f) (not (%memq? (first f) (Pin %pin-platform-heads))) #f))
                 forms)))
    ; The default project directory for the verbs: "." unless given.
    (method %pin-dir-or-dot (self dir)
      (match ((null? dir) ".") (#t (first dir))))
    ; root/src out of a manifest, with the message a project hits when the
    ; form it needs is simply not there -- naming the form, not the failure.
    (method %pin-need (self head forms dir)
      (let ((v (Pin %pin-manifest-arg head forms dir)))
            (match
              ((null? v) (Pin %pin-bad (Str8 append "manifest has no ("
                                                (Str8 append (symbol->str head)
                                                             " \"...\") form"))))
              (#t v))))
    ; Distinct module-name strings out of a closure's entries.
    (method %pin-closure-names (self entries)
      (def %go
            (fn (self lst acc)
              (match
                ((null? lst) acc)
                (#t
                  (let ((nm (Pin %pin-rel-name (first (first lst)))))
                    (match
                      ((%member-str? nm acc) (self (rest lst) acc))
                      (#t (self (rest lst) (pair nm acc)))))))))
          (%go entries ()))
    (method %pin-selected-paths (self entries)
      (def %go
            (fn (self lst acc)
              (match
                ((null? lst) acc)
                (#t (self (rest lst)
                          (pair (Pin %pin-path-norm (rest (first lst))) acc))))))
          (%go entries ()))
    (method %pin-unselected (self names selected)
      (def %per-name
            (fn (self names acc)
              (match
                ((null? names) acc)
                (#t
                  (self (rest names)
                    (Pin %pin-append-new acc
                      (Pin %pin-not-in (Pin %pin-name-candidates (first names)) selected)))))))
          (%per-name names ()))
    ; --- Version observability (GH #214 follow-up) -----------------------
    ; rel "maze/grid@1.3.1.x" or "maze/grid.x" -> the module name string.
    (method %pin-rel-name (self rel)
      (let ((at (Str8 index-of "@" rel)))
            (match
              ((null? at) (Str8 sub 0 (- (Str8 length rel) 2) rel))
              (#t (Str8 sub 0 at rel)))))
    ; Every candidate file for a module name string, across ALL import roots:
    ; the version files the kernel-direct scan sees, plus the bare file where
    ; present.  Full normalised paths.
    (method %pin-name-candidates (self namestr)
      (let ((reldir (%path-dir namestr))
                (base (Path basename namestr)))
            (def %per-root
              (fn (self roots acc)
                (match
                  ((null? roots) acc)
                  (#t
                    (let ((dir (%path-join (first roots) reldir)))
                      (self (rest roots)
                        (Pin %pin-append-new acc
                          (Pin %pin-cand-paths dir (%module-scan-dir dir base)))))))))
            (%per-root (first %import-roots-cell) ())))
    (method %pin-cand-paths (self dir cands)
      (def %rec (fn (self dir cands)
        (match
              ((null? cands) ())
              (#t (pair (Pin %pin-path-norm (%path-join dir (rest (first cands))))
                        (self dir (rest cands)))))))
      (%rec dir cands))
    ; The running dialect's boot entry, for init's default: pin what you are
    ; standing on.  %lang-name is set by each dialect body (helium/xenon/
    ; radon); bare boots leave it unset -- guard, and default to helium.
    (method %pin-running-entry (self)
      (let ((n (guard (_ ()) %lang-name)))
            (match
              ((null? n) (lit he))
              ((str=? n "helium") (lit he))
              ((str=? n "xenon") (lit xe))
              ((str=? n "radon") (lit rn))
              (#t (lit he)))))
    ; init's optionals, any order: a string is the project directory, a
    ; symbol is the boot entry.  Anything else is a loud error.
    (method %pin-init-opts (self opts dir entry)
      (def %rec (fn (self opts dir entry)
        (match
              ((null? opts) (pair dir entry))
              ((str? (first opts)) (self (rest opts) (first opts) entry))
              ((symbol? (first opts)) (self (rest opts) dir (first opts)))
              (#t (Pin %pin-bad "init: arguments are a directory string and/or an entry symbol")))))
      (%rec opts dir entry))
    (method %pin-init-template (self entry)
      (Str8 append
      "; What this project is pinned to.
      ;   root -- the overlay: this project's own copy of the library modules it imports
      ;   src  -- the tree the pin verbs scan to work out what those are
      ;   boot -- the language itself: a verified amalgam from a release
      (root \"deps\")
      (src \".\")
      (boot \"boot/"
            (Str8 append (symbol->str entry) ".x\")\n")))
    (method %pin-take-module (self name)
      (match
            ((%memq? name %pin-floor) ())  ; platform floor: inert if vendored
            ((%memq? name (first (Pin %pin-visited-cell))) ())
            (#t
              ; push BEFORE walking -- cycle safety, mirrors import itself
              (do (Pin %pin-push! (Pin %pin-visited-cell) name)
                  (let ((rel (Str8 append (symbol->str name) ".x")))
                    (let ((src (%module-resolve name)))
                      (do (Pin %pin-push! (Pin %pin-out-cell) (pair rel src))
                          (Pin %pin-walk-file rel src))))))))
    ; A versioned import: resolve name+spec through the BOOT layer's own
    ; resolver (one resolver, two consumers -- the same boot-level-accessor
    ; pattern take-module already uses for %module-resolve), then vendor the
    ; CHOSEN file at its versioned rel.  Dedup is by rel: each version file is
    ; its own overlay entry, and a bare (import name) elsewhere in the closure
    ; vendors the bare file alongside -- coexistence is the point; whether a
    ; PROJECT mixes versions is the audit's question, not the walk's.
    (method %pin-take-version (self who name spec)
      (let ((hit (%module-resolve-version who name
                       (%module-parse-spec who spec) spec)))
            (let ((rel (%path-join (%path-dir (symbol->str name))
                                   (Path basename (rest hit)))))
              (match
                ((Pin %pin-out-has? rel) ())
                (#t
                  (do (Pin %pin-push! (Pin %pin-out-cell) (pair rel (rest hit)))
                      (Pin %pin-walk-file rel (rest hit))))))))
    (method %pin-walk-file (self rel src)
      (Pin %pin-scan-list (Pin %pin-forms (File read-all src))
                          (pair (%path-dir rel) (%path-dir src))))
    (method %pin-tf-walk (self path rel acc)
      (def %names (guard (_ 'file) (File list-dir path)))
          (match
            ((eq? %names 'file) (pair rel acc))
            (#t (Pin %pin-tf-each path rel %names acc))))
    (method %pin-tf-each (self path rel lst acc)
      (def %rec (fn (self path rel lst acc)
        (match
              ((null? lst) acc)
              (#t (self path rel (rest lst)
                    (Pin %pin-tf-walk (%path-join path (first lst))
                                  (%path-join rel (first lst)) acc))))))
      (%rec path rel lst acc))
    ; scan-form/scan-list: mutually recursive PER TREE NODE.  One local fn,
    ; mode-discriminated, recursing only through its own self parameter --
    ; the TCO-safe spelling of mutual recursion (per-activation state rides
    ; PARAMS; cross-references between activation-local fns are not
    ; reliable, and a dispatch per node through the ~110-entry statics
    ; table timed out the ASan CI leg).
    (method %pin-scan-pair (self which arg dirs)
      (def %scan (fn (self which form dirs)
        (match
          ((eq? which (lit form))
            (match
                  ((not (pair? form)) ())
                  ((eq? (first form) 'lit) ())
                  ((eq? (first form) 'import)
                    (match
                      ; The argument check must come FIRST: (first (rest form)) on an
                      ; argument-less form derefs nil, so reaching for it inside the
                      ; guard that rejects it crashes instead of erroring.
                      ((not (pair? (rest form))) (Pin %pin-bad "import with no module name in closure"))
                      ((symbol? (first (rest form))) (Pin %pin-take-module (first (rest form))))
                      (#t (Pin %pin-bad "computed import name in closure"))))
                  ((or (eq? (first form) 'import-version) (eq? (first form) 'import-version-once))
                    (match
                      ((not (pair? (rest form))) (Pin %pin-bad "import-version with no module name in closure"))
                      ((not (symbol? (first (rest form)))) (Pin %pin-bad "computed import-version name in closure"))
                      ((not (pair? (rest (rest form)))) (Pin %pin-bad "import-version with no version spec in closure"))
                      ((not (str? (first (rest (rest form))))) (Pin %pin-bad "computed import-version spec in closure"))
                      (#t (Pin %pin-take-version (first form) (first (rest form))
                                             (first (rest (rest form)))))))
                  ((Pin %pin-include-head? (first form))
                    (match
                      ((not (pair? (rest form))) (Pin %pin-bad "include with no path in closure"))
                      (#t
                        (let ((arg (first (rest form))))
                          (match
                            ((not (str? arg)) (Pin %pin-bad "computed include path in closure"))
                            ((Str8 starts? "./" arg)
                              (Pin %pin-take-rel dirs (Str8 sub 2 (- (Str8 length arg) 2) arg)))
                            (#t (Pin %pin-bad (Str8 append "unvendorable include path: " arg))))))))
                  (#t (do (self (lit form) (first form) dirs)
                          (self (lit form) (rest form) dirs)))))
          (#t
            (match
                  ((pair? form)
                    (do (self (lit form) (first form) dirs)
                        (self (lit list) (rest form) dirs)))
                  (#t ()))))))
      (%scan which arg dirs))

    (method %pin-scan-form (self form dirs) (Pin %pin-scan-pair (lit form) form dirs))
    (method %pin-scan-list (self forms dirs) (Pin %pin-scan-pair (lit list) forms dirs))
    ; The project-scan mutual pair, same one-fn mode-discriminated shape.
    (method %pin-scan-project-pair (self which arg)
      (def %scan (fn (self which form)
        (match
          ((eq? which (lit form))
            (match
                  ((not (pair? form)) ())
                  ((eq? (first form) 'lit) ())
                  ((eq? (first form) 'import)
                    (match
                      ; Same nil-deref guard as %pin-scan-form, and it matters more
                      ; here: this walk reads arbitrary project sources, where a
                      ; half-typed (import) is an ordinary typo, not a library bug.
                      ((not (pair? (rest form))) (Pin %pin-bad "import with no module name in project scan"))
                      ((symbol? (first (rest form))) (Pin %pin-take-module (first (rest form))))
                      (#t (Pin %pin-bad "computed import name in project scan"))))
                  ((or (eq? (first form) 'import-version) (eq? (first form) 'import-version-once))
                    (match
                      ((not (pair? (rest form))) (Pin %pin-bad "import-version with no module name in project scan"))
                      ((not (symbol? (first (rest form)))) (Pin %pin-bad "computed import-version name in project scan"))
                      ((not (pair? (rest (rest form)))) (Pin %pin-bad "import-version with no version spec in project scan"))
                      ((not (str? (first (rest (rest form))))) (Pin %pin-bad "computed import-version spec in project scan"))
                      (#t (Pin %pin-take-version (first form) (first (rest form))
                                             (first (rest (rest form)))))))
                  (#t (do (self (lit form) (first form))
                          (self (lit form) (rest form))))))
          (#t
            (match
                  ((pair? form)
                    (do (self (lit form) (first form))
                        (self (lit list) (rest form))))
                  (#t ()))))))
      (%scan which arg))

        (method %pin-scan-project-list (self forms) (Pin %pin-scan-project-pair (lit list) forms))
    (method closure (self (param name SYMBOL "Module name, e.g. x/type/dict"))
    (doc "The module's vendorable import closure: root-relative file paths (the module, its transitive imports, and any ./-relative include siblings), discovery order. Boot-floor modules -- pre-seeded under the running dialect, so inert in an overlay -- are excluded. Loud error on any path the static walk cannot resolve."
      (returns LIST "Root-relative file path strings")
      (sample "(Pin closure 'x/type/dict)" "(\"x/type/dict.x\" ...)"))
    (Pin %pin-rels (Pin %pin-closure-of name)))
    (method vendor (self (param dest STRING "Overlay root directory, e.g. \"deps\"")
                         (param name SYMBOL "Module name to pin"))
    (doc "Copy the module's import closure into dest, preserving the root-relative layout (dest/x/type/dict.x pins x/type/dict). Run from a fresh session with x/tool/pin imported FIRST, so the boot floor is exact. A boot-floor seed is refused: it is unpinnable under this dialect (the pin boundary). Returns the copied paths."
      (returns LIST "Root-relative file path strings copied")
      (sample "(Pin vendor \"deps\" 'x/type/dict)" "(\"x/type/dict.x\" ...)"))
    (match
      ((%memq? name %pin-floor)
        (Pin %pin-bad (Str8 append "unpinnable (boot floor): " (symbol->str name))))
      (#t
        (let ((entries (Pin %pin-closure-of name)))
          (let ((rels (Pin %pin-rels entries)))
            ; dest otherwise only ever appears as a side effect of copying
            ; a file into it, so an EMPTY closure left the lockfile write
            ; writing into a directory that was never created.
            (do (Pin %pin-mkdirs dest)
                (Pin %pin-copy-all! dest entries)
                (Pin %pin-report-dropped dest
                  (Pin %pin-lock-relock! dest (symbol->str name) rels))
                rels))))))
    (method vendor-project (self (param dest STRING "Overlay root directory, e.g. \"deps\"")
                                 (param srcdir STRING "Project source dir to scan, e.g. \"src\""))
    (doc "Vendor a whole project's import closure in one call: scan srcdir's *.x sources for every (import NAME), take the union of their closures, and copy it into dest with the lockfile updated -- the multi-import vendor. Run from a fresh session with x/tool/pin imported FIRST (unarmed), so names resolve to the platform being vendored FROM and the boot floor is exact; boot-floor seeds are skipped. Returns the copied paths."
      (returns LIST "Root-relative file path strings copied")
      (sample "(Pin vendor-project \"deps\" \"src\")" "(\"x/type/dict.x\" ...)"))
    (Pin %pin-vendor-project! dest srcdir srcdir))
    (method verify (self (param dest STRING "Overlay root directory"))
      (doc "Verify dest against its pin.lock.xon: every entry's digest must match, and every file in the tree must be listed -- an unlisted file is a rogue shadow ready to win root precedence. A missing lockfile, missing file, digest mismatch, or unlisted file is a loud error naming each offender. Returns the number of files verified."
        (returns INT "Files verified")
        (sample "(Pin verify \"deps\")" "5"))
      (match
        ((not (File exists? (Pin %pin-lock-path dest)))
          (Pin %pin-bad (Str8 append "no lockfile: " (Pin %pin-lock-path dest))))
        (#t
          (let ((lock (Pin %pin-lock-read dest)))
            (let ((fails (Pin %pin-verify-fails dest lock)))
              (match
                ((null? fails) (Pin %pin-length lock))
                (#t (Pin %pin-bad (Str8 append "verify failed\n" (Pin %pin-join-lines fails))))))))))
    (method audit (self (param dest STRING "Overlay root directory")
                        . (param srcdir STRING "Project source dir to scan; default \".\""))
    (doc "Cross-check an overlay against the project's real imports: scan srcdir's *.x sources for their union import closure and report every required file MISSING from dest. Each missing file is an import that silently falls through to the live platform -- a half-pin. Returns the missing root-relative paths (empty = complete) and prints a notice when non-empty; guard CI with (if (null? (Pin audit ...)) ok (error ...)). Run unarmed, like vendor-project."
      (returns LIST "Missing root-relative file paths (empty = complete pin)")
      (sample "(Pin audit \"deps\" \"src\")" "()"))
    (let ((src (match ((null? srcdir) ".") (#t (first srcdir)))))
      (let ((missing (Pin %pin-audit-missing dest (Pin %pin-rels (Pin %pin-project-closure src)))))
        (do (match
              ((null? missing) ())
              (#t (do (display $"pin: audit -- {(Pin %pin-length missing)} import(s) fall through to the platform (absent from {dest}):\n{(Pin %pin-join-lines missing)}\n"))))
            missing))))
    (method init (self . (param opts ANY "Optional, any order: a project directory string (default \".\") and a boot dialect entry symbol (default the running dialect)"))
      (doc "Write a starter pin.xon -- the manifest every other verb reads -- commented so it teaches its own vocabulary: (root \"deps\") (src \".\") (boot \"boot/<entry>.x\"). Writes intent only: no directories are made and nothing is downloaded (boot and sync do those, in that order). Refuses to overwrite an existing manifest. Returns the manifest's path."
        (returns STRING "Path of the written pin.xon")
        (sample "(Pin init)" "\"pin.xon\"")
        (sample "(Pin init \"myproj\" 'xe)" "\"myproj/pin.xon\""))
      (let ((parsed (Pin %pin-init-opts opts "." ())))
        (let ((d (first parsed))
              (entry (match ((null? (rest parsed)) (Pin %pin-running-entry))
                           (#t (rest parsed)))))
          (let ((p (%path-join d (Pin %pin-manifest-name))))
            (do
              (match
                ((File exists? p)
                  (Pin %pin-bad (Str8 append "manifest already exists: " p)))
                (#t ()))
              (File write-all p (Pin %pin-init-template entry))
              (display "pin: wrote " p "\n"
                       "pin: edit (src ...) if your code lives elsewhere, then:\n"
                       "  (Pin boot \"vX.Y.Z\")   pin the language\n"
                       "  (Pin sync)            pin what your code imports\n")
              p)))))
    (method sync (self . (param dir STRING "Project directory holding pin.xon; default \".\""))
      (doc "Bring the overlay in line with the project's code: read pin.xon, scan its (src ...) tree for every import, and vendor the union closure into its (root ...), rewriting the lockfile. Idempotent, and the whole update after a source file gains an import -- no module list to maintain by hand. Run unarmed (--no-pin), so names resolve to the platform being vendored FROM. Returns the vendored root-relative paths."
        (returns LIST "Root-relative file path strings now pinned")
        (sample "(Pin sync)" "(\"x/type/dict.x\" ...)"))
      (let ((d (Pin %pin-dir-or-dot dir)))
        (let ((forms (Pin %pin-manifest-forms d)))
          (Pin %pin-vendor-project! (Pin %pin-need 'root forms d)
                                (Pin %pin-need 'src forms d)
                                (Pin %pin-manifest-raw 'src forms)))))
    (method check (self . (param dir STRING "Project directory holding pin.xon; default \".\""))
      (doc "The whole integrity question in one call, for CI: the overlay must match its lockfile byte for byte (nothing edited, nothing unlisted), AND no import in the (src ...) tree may fall through to the live platform. A digest mismatch or unlisted file is a loud error; a fallen-through import is reported and returned. Returns the missing root-relative paths -- empty means the pin is complete and intact."
        (returns LIST "Imports absent from the overlay (empty = complete)")
        (sample "(Pin check)" "()"))
      (let ((d (Pin %pin-dir-or-dot dir)))
        (let ((forms (Pin %pin-manifest-forms d)))
          (let ((root (Pin %pin-need 'root forms d))
                (src (Pin %pin-need 'src forms d)))
            ; Verify first: it raises. An audit answer computed against an
            ; overlay whose bytes are already wrong would describe a tree
            ; that does not exist.
            (do (Pin verify root)
                (Pin audit root src))))))
    (method boot (self (param tag STRING "Release tag to pin the language to, e.g. \"v0.3.1-rc6\"")
                       . (param dir STRING "Project directory holding pin.xon; default \".\""))
      (doc "Pin the language itself to a release, in one step: read the manifest's (boot ...) path, fetch and verify that release's amalgam into place, and record the release tag, its ISA fingerprint and the amalgam's digest in the lockfile beside pin.xon. The release manifest is consumed, not kept -- its three facts live in the lock, so nothing generated is left in the boot directory. Returns the amalgam's path."
        (returns STRING "Path of the verified amalgam")
        (sample "(Pin boot \"v0.3.1-rc6\")" "\"boot/he.x\""))
      (let ((d (Pin %pin-dir-or-dot dir)))
        (let ((forms (Pin %pin-manifest-forms d)))
          (let ((bootpath (Pin %pin-need 'boot forms d))
                (root (Pin %pin-need 'root forms d)))
            (let ((bootdir (%path-dir bootpath))
                  (file (Path basename (Pin %pin-need 'boot forms d))))
              (do
                (Pin fetch bootdir tag (Pin %pin-entry-of file))
                ; Lift the release's facts into the lock, then remove the
                ; downloaded manifest: two records of the same thing drift.
                (let ((rel (%path-join bootdir (Pin %pin-release-name))))
                  (let ((m (Pin %pin-release-parse (Pin %pin-forms (File read-all rel)))))
                    (do
                      (Pin %pin-lock-set-platform! root
                        (list (list 'release tag)
                              (list 'isa (%assoc-get 'isa m))
                              (list 'boot file (Pin %pin-digest bootpath))))
                      (File unlink rel))))
                bootpath))))))
    (method resolve (self (param name SYMBOL "Module name, e.g. maze/grid")
                          (param spec STRING "Version spec, e.g. \"1.3.*\" or \"^1\""))
      (doc "The file an (import-version-once NAME \"SPEC\") would load, resolved against the CURRENT import roots without loading anything -- the dry run of a versioned import, as closure is of vendor. Run it where your program runs (armed, the overlay answers; unarmed, the platform does). A spec nothing satisfies is the same loud error the import raises."
        (returns STRING "Path of the file the spec selects")
        (sample "(Pin resolve 'maze/grid \"1.3.*\")" "\"maze/grid@1.3.1.x\""))
      (rest (%module-resolve-version (lit resolve) name
              (%module-parse-spec (lit resolve) spec) spec)))
    (method unused (self . (param srcdir STRING "Project source dir to scan; default \".\""))
      (doc "Version files no import in srcdir's sources selects -- the safe-removal list. Provably neutral: resolution takes the newest satisfying candidate per root, so a file this returns cannot change any scanned import's outcome by being removed (had it been able to win for some spec, it would already be selected). The answer is relative to the sources scanned: an external consumer's specs are invisible here. Run unarmed, like audit; prints a notice when non-empty."
        (returns LIST "Full paths of version files nothing scanned selects")
        (sample "(Pin unused \"maze\")" "(\"maze/grid@0.9.x\")"))
      (let ((src (Pin %pin-dir-or-dot srcdir)))
        (let ((entries (Pin %pin-project-closure src)))
          (let ((selected (Pin %pin-selected-paths entries))
                (names (Pin %pin-closure-names entries)))
            (let ((unused (Pin %pin-unselected names selected)))
              (do (match
                    ((null? unused) ())
                    (#t (do (display $"pin: unused -- {(Pin %pin-length unused)} version file(s) no scanned import selects (safe to remove):\n{(Pin %pin-join-lines unused)}\n"))))
                  unused))))))
    (method fetch (self (param dest STRING "Directory to fetch into")
                        (param tag STRING "Release tag, e.g. \"v0.4.0\"")
                        (param entry SYMBOL "Boot entry to fetch, e.g. 'xe")
                        . (param base STRING "Base URL; default the project's releases"))
      (doc "Fetch a released amalgam, verified or nothing: downloads the tag's pin.release.xon and <entry>.x (curl via fork/execvp -- absent curl prints the URLs and stops), checks the manifest names the tag, digests the amalgam with Sha256 -- the differentially-verified JIT engine where the host supports it (seconds), pure-x elsewhere (minutes for an amalgam; either way announced), and errors on any mismatch, naming the offending file (left in place for inspection; do not boot it). Reports whether the release's ISA fingerprint matches this tree's tools/contract/isa.x when present -- drift is information, not an error: a pinned platform pairs with its own engine. Returns the amalgam's path."
        (returns STRING "Path of the verified amalgam")
        (sample "(Pin fetch \"boot\" \"v0.4.0\" 'xe)" "\"boot/xe.x\""))
      (let ((b (match ((null? base) (Pin %pin-release-base)) (#t (first base)))))
        (let ((file (Str8 append (symbol->str entry) ".x")))
          (do
            (Pin %pin-mkdirs dest)
            (Pin %pin-download! (Pin %pin-url b tag (Pin %pin-release-name))
                            (%path-join dest (Pin %pin-release-name)))
            (let ((m (Pin %pin-release-parse
                       (Pin %pin-forms (File read-all (%path-join dest (Pin %pin-release-name)))))))
              (do
                (match
                  ((str=? (%assoc-get 'release m) tag) ())
                  (#t (Pin %pin-bad (Str8 append "manifest names another release: "
                                            (%assoc-get 'release m)))))
                (let ((want (Pin %pin-release-file file (%assoc-get 'files m)))
                      (target (%path-join dest file)))
                  (do
                    (Pin %pin-download! (Pin %pin-url b tag file) target)
                    ; Build the compiled digest only when the payload
                    ; justifies it: 65536 mirrors sha256.x's own
                    ; auto-build bar (%sha-jit-threshold).  An amalgam
                    ; (hundreds of KB) still gets the engine -- and the
                    ; slow-path warning when the build is unavailable --
                    ; while a small artifact digests pure-x in
                    ; milliseconds instead of paying the ~14.5s engine
                    ; build (#324: the pin gate's three fetch smokes
                    ; each paid it to verify tens of bytes).
                    (display "pin: verifying " target
                             (if (< (%assoc-get 'size (File stat target)) 65536)
                                 ""
                                 (if (Sha256 jit!)
                                     " (jit sha256)"
                                     " (pure x-lang sha256; an amalgam takes minutes)"))
                             "\n")
                    (match
                      ((str=? (Pin %pin-digest target) want) ())
                      (#t (Pin %pin-bad (Str8 append "digest mismatch: " target))))
                    (match
                      ((File exists? "tools/contract/isa.x")
                        (do (display (match
                                       ; A manifest may carry no (isa ...) at all --
                                       ; %pin-release-parse requires only the tag, so
                                       ; %pin-assoc hands back nil, and str=? on nil
                                       ; would die AFTER the amalgam verified clean.
                                       ; Drift is information, not an error (docstring),
                                       ; and so is an absent fingerprint.
                                       ((null? (%assoc-get 'isa m))
                                         "pin: the release manifest carries no isa fingerprint -- engine pairing unchecked")
                                       ((str=? (Pin %pin-digest "tools/contract/isa.x") (%assoc-get 'isa m))
                                         "pin: isa fingerprint matches this tree")
                                       (#t "pin: isa fingerprint DIFFERS from this tree -- pair the amalgam with its release's engine"))
                                     "\n")))
                      ; No local ISA manifest -- the reader case: an
                      ; unpacked tarball has no source checkout, so the
                      ; check above cannot run.  SAY so.  Silence here
                      ; reads as "pairing verified" to someone who just
                      ; watched the digest verify, and the pairing is
                      ; precisely what a platform pin is for.  Absent
                      ; information is information, the same ruling the
                      ; absent-fingerprint branch above already makes.
                      (#t
                        (do
                          (display "pin: no isa manifest here -- engine pairing unchecked (run from a source checkout to compare)\n"))))
                    target))))))))
))

; --- Load-time driver: a no-op unless the wrapper announced a manifest.
(let ((%pin-announced (guard (_ ()) %pin-file)))
  (match
    ((null? %pin-announced) ())
    (#t (Pin %pin-arm!
          (Pin %pin-interpret (Pin %pin-forms (File read-all %pin-announced))
                              (%path-dir %pin-announced))))))

(provide x/tool/pin Pin)
