; tools/contract/conformance-covered.x -- the ISA rows the conformance
; suite currently DEFINES.  Generated by tools/check/conformance-coverage.sh
; --update; do not hand-edit.
;
; A ratchet, not a target: coverage may grow freely, and a row that was
; covered and is no longer fails the gate.  The suite is early -- this file
; exists so that being early cannot be mistaken for being finished, and so
; that progress cannot silently reverse.
(def %conformance-covered (lit (
  (%)
  (&)
  (*)
  (+)
  (-)
  (/)
  (<)
  (<<)
  (=)
  (>>)
  (^)
  (apply)
  (call/cc)
  (def)
  (eq?)
  (error)
  (eval)
  (first)
  (fn)
  (guard)
  (lit)
  (match)
  (op)
  (pair)
  (rest)
  (same?)
  (set!)
  (|)
  (~)
)))
