#!/usr/bin/awk -f
# gen-base-layout.awk — convert the X slot descriptor into C.
#
#   awk -f tools/gen-base-layout.awk tools/base-layout.x
#
# tools/base-layout.x is the single source of truth for the x-eval base
# object's pair-tree layout.  This script transcribes it into C two ways:
#   * ACCESSORS    — the x_eval_* / x_eval_field_* reader macros
#   * CONSTRUCTION — the pure structural skeleton assigned in x_eval_make
# Initial VALUES are not structure; they stay in a hand-written init pass
# that fills the value cells through the generated accessors.  The same file
# is valid X and is read as data by the X layer, so the two cannot drift.

BEGIN {
	PREFIX = "x_eval"
	# Top-level roots map onto x-expr's documented extension anchors.
	ANCHOR["base"]       = "x_base"
	ANCHOR["io-group"]   = "x_base_field_io_group"
	ANCHOR["profile"]    = "x_base_field_profile"
	ANCHOR["meta-group"] = "x_base_field_meta_group"
}

# Accumulate source, stripping ';' line comments.
{ line = $0; sub(/;.*/, "", line); src = src " " line }

END {
	gsub(/\(/, " ( ", src); gsub(/\)/, " ) ", src)
	n = split(src, a, /[ \t\r\n]+/)
	for (i = 1; i <= n; i++)
		if (a[i] != "")
			tok[++ntok] = a[i]

	print "/* GENERATED by tools/gen-base-layout.awk from tools/base-layout.x."
	print " * DO NOT EDIT -- edit the descriptor and regenerate (make gen-layout)."
	print " *"
	print " * Accessors are include-guarded (use normally).  The construction"
	print " * skeleton is emitted only when X_EVAL_BUILD_TREE is defined before"
	print " * inclusion -- x_eval_make does that to build the empty pair tree;"
	print " * initial values are set by the hand-written init pass after it. */"
	print ""
	print "#ifndef X_EVAL_LAYOUT_H"
	print "#define X_EVAL_LAYOUT_H"
	ti = 1; while (ti <= ntok) walk("acc", "", "")
	print "#endif /* X_EVAL_LAYOUT_H */"
	print ""
	print "#ifdef X_EVAL_BUILD_TREE"
	ti = 1; while (ti <= ntok) walk("con", "", "")
	print "#endif /* X_EVAL_BUILD_TREE */"
}

# Traverse one node.  `mode` is "acc" (reader macros) or "con" (construction
# assignments).  `anchor` is the nearest enclosing anchor macro; `path` is the
# car/cdr route (car=0, cdr=1) from it to here.
function walk(mode, anchor, path,    tag, name, mine, kind) {
	expect("(")
	tag = tok[ti++]

	if (tag == "node") {
		name = tok[ti++]
		if (name in ANCHOR) {
			mine = ANCHOR[name]                     # external x-expr anchor
		} else {
			mine = PREFIX "_" cid(name)
			if (mode == "acc")
				printf "#define %s(X)\t%s\n", mine, navwrap(path, anchor "(X)")
		}
		walk(mode, mine, "0")
		walk(mode, mine, "1")
		expect(")")
	} else if (tag == "pair") {
		walk(mode, anchor, path "0")
		walk(mode, anchor, path "1")
		expect(")")
	} else if (tag == "cell" || tag == "slot") {
		name = tok[ti++]
		if (mode == "acc") {
			kind = (tag == "cell") ? "cell" : "direct"
			printf "#define %s_field_%s(X)\t%s\t/* %s */\n", \
				PREFIX, cid(name), navwrap(path, anchor "(X)"), kind
		}
		expect(")")
	} else if (tag == "build") {
		if (mode == "con")
			printf "\t%s = %s;\n", navwrap(path, anchor "(p_base)"), buildexpr()
		else
			walk(mode, anchor, path)                # transparent: recurse in
		expect(")")
	} else if (tag == "nil") {
		expect(")")
	} else if (tag == "todo") {
		ti++
		expect(")")
	} else {
		print "PARSE ERROR: unknown tag '" tag "'" > "/dev/stderr"
		exit 1
	}
}

# Consume one subtree; return the C expression that builds its empty skeleton.
function buildexpr(    tag, s) {
	expect("(")
	tag = tok[ti++]
	if (tag == "node") { ti++; s = "pair(" buildexpr() ", " buildexpr() ")"; expect(")"); return s }
	if (tag == "pair") {       s = "pair(" buildexpr() ", " buildexpr() ")"; expect(")"); return s }
	if (tag == "cell") { ti++; expect(")"); return "pair(nil, nil)" }
	if (tag == "slot") { ti++; expect(")"); return "nil" }
	if (tag == "nil")  {       expect(")"); return "nil" }
	print "PARSE ERROR: bad tag in build '" tag "'" > "/dev/stderr"
	exit 1
}

# Wrap `inner` with the car/cdr route `d` (root->leaf, car=0 cdr=1).  The x_NN
# macros read OUTER->inner, so reverse d first (x_01 == car(cdr)); then, since
# x-obj.h only defines up to x_1111, chunk into <=4-digit macros, leftmost
# (outermost) chunk last.
function navwrap(d, inner,    rd, L, i, ng, g, k) {
	rd = ""
	for (i = length(d); i >= 1; i--)
		rd = rd substr(d, i, 1)
	L = length(rd)
	if (L == 0)
		return inner
	ng = 0
	for (i = 1; i <= L; i += 4)
		g[++ng] = substr(rd, i, 4)
	for (k = ng; k >= 1; k--)
		inner = "x_" g[k] "(" inner ")"
	return inner
}

# X uses kebab-case (env-alist); C identifiers use snake_case (env_alist).
function cid(name,    s) { s = name; gsub(/-/, "_", s); return s }

function expect(s,    t) {
	t = tok[ti++]
	if (t != s) {
		print "PARSE ERROR: expected '" s "' got '" t "'" > "/dev/stderr"
		exit 1
	}
}
