; percent-globals.x -- the %-global budget, per file: (file "PATH" COUNT)
; May only SHRINK (tools/check/percent-globals.sh).  A file absent here
; has budget 0.  The composed alternative: home helpers as %-statics on
; the module's class (classes ARE namespaces; pin.x is the worked
; example -- 100 globals homed to 1).
;
; Hot-path rows stand on MEASURED de-dispatch grounds (8-30x class
; call overhead): sha256*, asm*, compile*, boot/*.  Everything else is
; unhomed inventory awaiting the pin.x treatment.
(file "lib/x/boot/data.x" 15)
(file "lib/x/boot/module.x" 52)
(file "lib/x/boot/operatives.x" 6)
(file "lib/x/boot/printer.x" 76)
(file "lib/x/boot/reflect.x" 29)
(file "lib/x/boot/registry.x" 8)
(file "lib/x/boot/string.x" 18)
(file "lib/x/boot/tower-compiled.x" 12)
(file "lib/x/codec/json.x" 30)
(file "lib/x/codec/sha256-jit.x" 34)
(file "lib/x/codec/sha256.x" 33)
(file "lib/x/codec/utf8.x" 6)
(file "lib/x/core/alist.x" 5)
(file "lib/x/core/arithmetic.x" 17)
(file "lib/x/core/boolean.x" 3)
(file "lib/x/core/control.x" 2)
(file "lib/x/core/list.x" 8)
(file "lib/x/core/logic.x" 1)
(file "lib/x/core/math.x" 5)
(file "lib/x/core/op-guard.x" 6)
(file "lib/x/core/predicates.x" 12)
(file "lib/x/core/quasi.x" 1)
(file "lib/x/core/syntax.x" 5)
(file "lib/x/doc/doc-gen.x" 25)
(file "lib/x/doc/doc.x" 73)
(file "lib/x/num/bignum.x" 57)
(file "lib/x/num/complex.x" 41)
(file "lib/x/num/float.x" 60)
(file "lib/x/num/random.x" 5)
(file "lib/x/num/rational.x" 39)
(file "lib/x/platform/socket.x" 1)
(file "lib/x/platform/syscall.x" 5)
(file "lib/x/protocol/seq.x" 1)
(file "lib/x/protocol/str/str8.x" 14)
(file "lib/x/protocol/str/utf8.x" 5)
(file "lib/x/reader/intrinsics.x" 5)
(file "lib/x/reader/lit-reader.x" 22)
(file "lib/x/reader/quasi-reader.x" 10)
(file "lib/x/reader/token.x" 14)
(file "lib/x/repl/ansi.x" 26)
(file "lib/x/repl/banner.x" 4)
(file "lib/x/repl/loop.x" 12)
(file "lib/x/rn.x" 1)
(file "lib/x/sys/date.x" 6)
(file "lib/x/sys/file.x" 12)
(file "lib/x/sys/pact.x" 12)
(file "lib/x/sys/posix.x" 32)
(file "lib/x/sys/socket.x" 29)
(file "lib/x/sys/stream.x" 5)
(file "lib/x/tool/asm-compile.x" 62)
(file "lib/x/tool/asm.x" 37)
(file "lib/x/tool/asm/arm64.x" 8)
(file "lib/x/tool/asm/x86_64.x" 23)
(file "lib/x/tool/compile.x" 22)
(file "lib/x/tool/compile/emit.x" 54)
(file "lib/x/tool/compile/pipeline.x" 10)
(file "lib/x/tool/contract.x" 4)
(file "lib/x/tool/cov.x" 8)
(file "lib/x/tool/fmt.x" 22)
(file "lib/x/tool/lint.x" 68)
(file "lib/x/tool/pin.x" 1)
(file "lib/x/tool/profile.x" 4)
(file "lib/x/type/array.x" 2)
(file "lib/x/type/assoc.x" 1)
(file "lib/x/type/bool.x" 5)
(file "lib/x/type/char-io.x" 11)
(file "lib/x/type/char.x" 5)
(file "lib/x/type/class.x" 72)
(file "lib/x/type/convert.x" 20)
(file "lib/x/type/dict.x" 13)
(file "lib/x/type/err.x" 6)
(file "lib/x/type/gen.x" 1)
(file "lib/x/type/hash.x" 4)
(file "lib/x/type/iter.x" 19)
(file "lib/x/type/list.x" 5)
(file "lib/x/type/path.x" 2)
(file "lib/x/type/promise.x" 6)
(file "lib/x/type/ptr.x" 3)
(file "lib/x/type/regex.x" 41)
(file "lib/x/type/str-utf8.x" 12)
(file "lib/x/type/struct.x" 48)
(file "lib/x/type/vector.x" 17)
