; percent-globals.x -- the %-global budget, per file: (file "PATH" COUNT)
; May only SHRINK (tools/check/percent-globals.sh).  A file absent here
; has budget 0.  The composed alternative: home helpers as %-statics on
; the module's class (classes ARE namespaces; pin.x is the worked
; example -- 100 globals homed to 1).
;
; Scope is lib/ + apps/ + tools/ (#304): a tool script co-loads with the
; library, so its globals share the env.  Counting is form-accurate
; (tools/check/defs.awk), which sees two shapes the old line grep did
; not -- (doc (def %name ...)), so DOCUMENTED helpers stopped hiding, and
; defs directly inside a top-level (do ...), which is how tool scripts
; are written.  Rows that grew when the blind spots closed record
; globals that were always there, not new pollution.
;
; Hot-path rows stand on MEASURED de-dispatch grounds (8-30x class
; call overhead): sha256*, asm*, compile*, boot/*, and (#334: 15x on
; the fnv byte loop, 2x on dict ops, benchmarked) type/dict + type/hash,
; and (#335: cached int %// on the random draw loop, port math, and the
; per-expression gc tick) num/random + sys/socket + tool/asm-compile,
; and (#307: the sugar-fold cell reads per PRINTED NODE) tool/fmt.
; The type/class.x row GROWS during the object-model v2 arc (plan
; approved 2026-08-20): the dispatch engine's own helpers are the
; measured hot path (8-30x, #332) the exception above exists for --
; each growth step is one warm-path helper, named per commit.
; Everything else is unhomed inventory awaiting the pin.x treatment.
(file "apps/logo/dispatch.x" 28)
(file "apps/logo/entry.x" 27)
(file "apps/logo/expr.x" 15)
(file "apps/logo/indent.x" 2)
(file "apps/logo/json.x" 1)
(file "apps/logo/main.x" 6)
(file "apps/logo/math.x" 5)
(file "apps/logo/repl.x" 9)
(file "apps/logo/serve.x" 15)
(file "apps/logo/state.x" 15)
(file "apps/logo/tstate.x" 2)
(file "apps/logo/types.x" 43)
(file "lib/x/boot/data.x" 14)
(file "lib/x/boot/module.x" 52)
(file "lib/x/boot/operatives.x" 6)
(file "lib/x/boot/printer.x" 76)
(file "lib/x/boot/reflect.x" 29)
(file "lib/x/boot/registry.x" 8)
(file "lib/x/boot/string.x" 25)
(file "lib/x/boot/tower-compiled.x" 12)
(file "lib/x/codec/json.x" 30)
(file "lib/x/codec/sha256-jit.x" 34)
(file "lib/x/codec/sha256.x" 33)
(file "lib/x/codec/utf8.x" 6)
(file "lib/x/core/alist.x" 12)
(file "lib/x/core/arithmetic.x" 17)
(file "lib/x/core/boolean.x" 3)
(file "lib/x/core/control.x" 2)
(file "lib/x/core/list.x" 19)
(file "lib/x/core/logic.x" 1)
(file "lib/x/core/math.x" 5)
(file "lib/x/core/op-guard.x" 6)
(file "lib/x/core/predicates.x" 12)
(file "lib/x/core/quasi.x" 1)
(file "lib/x/core/syntax.x" 5)
(file "lib/x/doc/doc-gen.x" 32)
(file "lib/x/doc/doc.x" 73)
(file "lib/x/num/bigint.x" 57)
(file "lib/x/num/complex.x" 41)
(file "lib/x/num/float.x" 60)
(file "lib/x/num/random.x" 6)
(file "lib/x/num/rational.x" 39)
(file "lib/x/platform/socket.x" 1)
(file "lib/x/platform/syscall.x" 5)
(file "lib/x/protocol/seq.x" 1)
(file "lib/x/protocol/str/str8.x" 14)
(file "lib/x/protocol/str/utf8.x" 5)
(file "lib/x/reader/intrinsics.x" 5)
(file "lib/x/reader/lit-reader.x" 21)
(file "lib/x/reader/quasi-reader.x" 9)
(file "lib/x/reader/analyser.x" 14)
(file "lib/x/repl/ansi.x" 26)
(file "lib/x/repl/banner.x" 4)
(file "lib/x/repl/loop.x" 12)
(file "lib/x/rn.x" 1)
(file "lib/x/sys/date.x" 6)
(file "lib/x/sys/file.x" 7)
(file "lib/x/sys/pact.x" 12)
(file "lib/x/sys/posix.x" 32)
(file "lib/x/sys/socket.x" 31)
(file "lib/x/sys/stream.x" 5)
(file "lib/x/tool/asm-compile.x" 63)
(file "lib/x/tool/asm.x" 37)
(file "lib/x/tool/asm/arm64.x" 8)
(file "lib/x/tool/asm/x86_64.x" 23)
(file "lib/x/tool/compile.x" 24)
(file "lib/x/tool/compile/emit.x" 54)
(file "lib/x/tool/compile/pipeline.x" 10)
(file "lib/x/tool/contract.x" 4)
(file "lib/x/tool/cov.x" 8)
(file "lib/x/tool/fmt.x" 23)
(file "lib/x/tool/lint.x" 69)
(file "lib/x/tool/pin.x" 1)
(file "lib/x/tool/profile.x" 4)
(file "lib/x/type/array.x" 2)
(file "lib/x/type/assoc.x" 1)
(file "lib/x/type/bool.x" 5)
(file "lib/x/type/char-io.x" 11)
(file "lib/x/type/char.x" 5)
(file "lib/x/type/record.x" 3)
(file "lib/x/type/trait.x" 6)
(file "lib/x/type/class.x" 89)
(file "lib/x/type/convert.x" 20)
(file "lib/x/type/dict.x" 19)
(file "lib/x/type/err.x" 6)
(file "lib/x/type/gen.x" 1)
(file "lib/x/type/generic.x" 19)
(file "lib/x/type/hash.x" 7)
(file "lib/x/type/iter.x" 19)
(file "lib/x/type/list.x" 5)
(file "lib/x/type/path.x" 2)
(file "lib/x/type/promise.x" 6)
(file "lib/x/type/ptr.x" 3)
(file "lib/x/type/regex.x" 41)
(file "lib/x/type/str-utf8.x" 14)
(file "lib/x/type/struct.x" 48)
(file "lib/x/type/vector.x" 17)
(file "tools/check/boot-order.x" 33)
(file "tools/check/dialect-cover.x" 9)
(file "tools/check/doctest.x" 11)
(file "tools/contract/bare-globals.x" 1)
(file "tools/contract/base-paths.x" 1)
(file "tools/contract/isa.x" 5)
(file "tools/contract/obj-layout.x" 29)
(file "tools/dev/bench-sha256.x" 75)
(file "tools/dev/cov-report.x" 5)
(file "tools/dev/cov.x" 32)
(file "tools/dev/doc-index.x" 10)
(file "tools/dev/doc.x" 3)
(file "tools/dev/fmt.x" 13)
(file "tools/dev/lint.x" 22)
