; private-reads.x -- the cross-file private-read budget, per reader file:
; (file "PATH" COUNT).  May only shrink (tools/check/private-reads.sh).
;
; COUNT is the number of distinct % names the file reads that some OTHER
; unscoped file defines at its top level and the file does not define
; itself.  Each is a coupling that scoping the owner breaks, and step 4 of
; x-lang#719 is spent replacing them with doors: a class static where the
; owner has a class, a catalog entry where it loads before the object
; system, an export the reader imports where the owner is scoped.  A row
; goes down as its file's reads become doors, and a file absent here reads
; none.
;
; Recorded 2026-09-21 at 0c7f67b0: 127 files, 954 reads.  The largest rows
; are the number tower reading its neighbours (tower, complex, decimal,
; bigint, float, rational), boot/tower-compiled and the compiler's stages,
; which resolve free names in the root by design, and the dev tools
; (image-write, lint), which drive the library's internals directly.
(file "apps/bitwise/cli.x" 5)
(file "apps/bitwise/gen.x" 10)
(file "apps/bitwise/run.x" 1)
(file "lib/he.x" 2)
(file "lib/rn.x" 2)
(file "lib/x-core.x" 3)
(file "lib/x.x" 2)
(file "lib/x/boot/helium.x" 4)
(file "lib/x/boot/module.x" 7)
(file "lib/x/boot/printer.x" 20)
(file "lib/x/boot/radon.x" 4)
(file "lib/x/boot/reflect.x" 18)
(file "lib/x/boot/tower-compiled.x" 6)
(file "lib/x/boot/xenon.x" 4)
(file "lib/x/codec/base64.x" 1)
(file "lib/x/codec/csv.x" 1)
(file "lib/x/codec/hex.x" 1)
(file "lib/x/codec/json.x" 4)
(file "lib/x/codec/sha256.x" 3)
(file "lib/x/codec/struct.x" 1)
(file "lib/x/codec/utf8.x" 1)
(file "lib/x/codec/xon.x" 11)
(file "lib/x/codec/zlib.x" 2)
(file "lib/x/core/alist.x" 1)
(file "lib/x/core/arithmetic.x" 2)
(file "lib/x/core/math.x" 2)
(file "lib/x/core/quasi.x" 3)
(file "lib/x/core/syntax.x" 2)
(file "lib/x/doc/doc-gen.x" 11)
(file "lib/x/doc/doc.x" 8)
(file "lib/x/doc/emit-man.x" 1)
(file "lib/x/doc/emit.x" 1)
(file "lib/x/net/http.x" 3)
(file "lib/x/net/tls.x" 1)
(file "lib/x/num/bigint.x" 14)
(file "lib/x/num/complex.x" 6)
(file "lib/x/num/decimal.x" 9)
(file "lib/x/num/float.x" 7)
(file "lib/x/num/random.x" 1)
(file "lib/x/num/rational.x" 10)
(file "lib/x/num/tower.x" 1)
(file "lib/x/platform/dirent.x" 1)
(file "lib/x/platform/syscall.x" 3)
(file "lib/x/protocol/seq.x" 4)
(file "lib/x/protocol/str/str8.x" 5)
(file "lib/x/protocol/str/utf8.x" 1)
(file "lib/x/reader/analyser.x" 4)
(file "lib/x/reader/intrinsics.x" 3)
(file "lib/x/reader/lit-reader.x" 5)
(file "lib/x/reader/quasi-reader.x" 3)
(file "lib/x/repl/ansi.x" 14)
(file "lib/x/repl/banner.x" 1)
(file "lib/x/repl/lang.x" 14)
(file "lib/x/repl/launch.x" 1)
(file "lib/x/repl/line.x" 16)
(file "lib/x/repl/loop.x" 5)
(file "lib/x/repl/paint.x" 6)
(file "lib/x/repl/term.x" 1)
(file "lib/x/rn.x" 2)
(file "lib/x/sys/date.x" 2)
(file "lib/x/sys/file.x" 2)
(file "lib/x/sys/opts.x" 3)
(file "lib/x/sys/posix.x" 8)
(file "lib/x/sys/proc.x" 2)
(file "lib/x/sys/socket.x" 4)
(file "lib/x/sys/stream.x" 2)
(file "lib/x/tool/asm-cache.x" 8)
(file "lib/x/tool/asm-compile.x" 16)
(file "lib/x/tool/asm.x" 3)
(file "lib/x/tool/asm/arm64.x" 4)
(file "lib/x/tool/asm/x86_64.x" 9)
(file "lib/x/tool/compile.x" 8)
(file "lib/x/tool/compile/emit.x" 7)
(file "lib/x/tool/compile/pipeline.x" 4)
(file "lib/x/tool/cov.x" 5)
(file "lib/x/tool/fmt.x" 3)
(file "lib/x/tool/lint.x" 11)
(file "lib/x/tool/pin.x" 21)
(file "lib/x/tool/profile.x" 4)
(file "lib/x/type/assoc.x" 11)
(file "lib/x/type/base.x" 2)
(file "lib/x/type/block.x" 12)
(file "lib/x/type/bool.x" 2)
(file "lib/x/type/char.x" 1)
(file "lib/x/type/class.x" 17)
(file "lib/x/type/convert.x" 4)
(file "lib/x/type/deque.x" 1)
(file "lib/x/type/dict.x" 1)
(file "lib/x/type/err-io.x" 1)
(file "lib/x/type/err.x" 4)
(file "lib/x/type/gen.x" 2)
(file "lib/x/type/generic.x" 6)
(file "lib/x/type/hash.x" 1)
(file "lib/x/type/iter.x" 4)
(file "lib/x/type/list.x" 6)
(file "lib/x/type/path.x" 2)
(file "lib/x/type/promise.x" 1)
(file "lib/x/type/record.x" 2)
(file "lib/x/type/regex.x" 14)
(file "lib/x/type/str-utf8.x" 4)
(file "lib/x/type/struct.x" 5)
(file "lib/x/type/trait.x" 2)
(file "lib/x/type/type.x" 8)
(file "lib/x/type/vector.x" 5)
(file "lib/xe.x" 2)
(file "tools/check/boot-order.x" 8)
(file "tools/check/dialect-cover.x" 2)
(file "tools/check/doc-forms.x" 1)
(file "tools/check/doctest.x" 6)
(file "tools/check/engine-contract.x" 11)
(file "tools/contract/seam.x" 12)
(file "tools/dev/bench-sha256.x" 9)
(file "tools/dev/cov-report.x" 4)
(file "tools/dev/cov.x" 7)
(file "tools/dev/doc.x" 2)
(file "tools/dev/fmt.x" 11)
(file "tools/dev/highlight.x" 1)
(file "tools/dev/image-foreign.x" 14)
(file "tools/dev/image-inspect.x" 10)
(file "tools/dev/image-name.x" 6)
(file "tools/dev/image-read.x" 12)
(file "tools/dev/image-walk.x" 4)
(file "tools/dev/image-write.x" 43)
(file "tools/dev/lint.x" 21)
(file "tools/dev/nul-escape.x" 1)
(file "tools/fuzz/diff-gen.x" 2)
