#!/bin/sh
# conformance-coverage.sh -- how much of the ISA does the conformance suite define?
#
#   Usage: sh tools/check/conformance-coverage.sh [--update]
#
# The conformance suite is x-lang's executable definition of what an engine must
# do.  It starts from nothing (the bare smoke harness that used to live here moved
# to the engine, deliberately -- it answered a different question), so the useful
# gate is not "is it complete" but "did it just get smaller".
#
# THE RATCHET.  tools/contract/conformance-covered.x lists the ISA rows the suite
# currently defines.  Coverage may GROW freely; a row that was covered and is no
# longer fails this check.  That is the same shape as the %-global budgets, pointed
# at a suite instead of at globals, and it is the honest gate for work that will
# take many sittings: it cannot claim completeness it does not have, and it cannot
# quietly regress.
#
# A row is covered when some spec section names it on a `covers:` line.  Naming is
# explicit rather than inferred from the source, for the reason the constraint
# markers are explicit: a scan that guessed which primitive a case exercised would
# be confidently wrong on exactly the cases that matter (a case that reaches `+`
# through three layers of helper is not a test of `+`).
#
# UNCOVERED IS REPORTED, NOT FAILED.  The remaining rows are printed every run.  A
# suite that is silent about its gaps reads as complete, and this one is at the
# beginning of a long job.
set -e

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
SUITE="tests/x/conformance"
ISA="engine/tools/contract/isa.x"
FLOOR="tools/contract/conformance-covered.x"
[ -f "$ISA" ] || { echo "conformance-coverage: no engine ISA at $ISA" >&2; exit 2; }

W="${TMPDIR:-/tmp}/confcov.$$"; mkdir -p "$W"
trap 'rm -rf "$W"' EXIT INT TERM

# --- the surface: every ISA row, as the `covers:` lines spell it -------------
# Catalog rows are ns/method; bare and keep rows are the bare name.  Values and
# aliases are not instructions and carry no obligation.
awk '
	/^\(def %isa-catalog/ { s="catalog"; next }
	/^\(def %isa-bare/    { s="bare";    next }
	/^\(def %isa-keep/    { s="keep";    next }
	/^\(def %isa-aliases/ { s="";        next }
	/^\(def %isa-values/  { s="";        next }
	/^  \(/ {
		if (s == "") next
		l = $0; sub(/;.*/, "", l); gsub(/[()]/, "", l); $0 = l
		if (s == "catalog" && NF >= 3) print $1 "/" $2
		else if (s != "catalog" && NF >= 1) print $1
	}' "$ISA" | sort -u > "$W/surface"

# --- what the suite claims to define ----------------------------------------
if [ -d "$SUITE" ]; then
	find "$SUITE" -name '*.spec.md' -exec cat {} + 2>/dev/null \
	  | awk '/^covers:/ { sub(/^covers:[ \t]*/, ""); n = split($0, f, /[ \t]+/)
	                      for (i = 1; i <= n; i++) if (f[i] != "") print f[i] }' \
	  | sort -u > "$W/covered"
else
	: > "$W/covered"
fi

# A `covers:` row naming something that is not in the ISA is a typo or a stale
# name, and would otherwise inflate the count silently.
comm -23 "$W/covered" "$W/surface" > "$W/bogus"
if [ -s "$W/bogus" ]; then
	echo "conformance-coverage: covers: names something the ISA does not have:"
	sed 's/^/    /' "$W/bogus"
	echo "FAIL: fix the name, or add the row to the engine's isa.x."
	exit 1
fi

comm -12 "$W/covered" "$W/surface" > "$W/real"
comm -13 "$W/covered" "$W/surface" > "$W/uncovered"
ntotal=$(wc -l < "$W/surface" | tr -d ' ')
ncov=$(wc -l < "$W/real" | tr -d ' ')

if [ "${1:-}" = "--update" ]; then
	{
		printf '; tools/contract/conformance-covered.x -- the ISA rows the conformance\n'
		printf '; suite currently DEFINES.  Generated by tools/check/conformance-coverage.sh\n'
		printf '; --update; do not hand-edit.\n;\n'
		printf '; A ratchet, not a target: coverage may grow freely, and a row that was\n'
		printf '; covered and is no longer fails the gate.  The suite is early -- this file\n'
		printf '; exists so that being early cannot be mistaken for being finished, and so\n'
		printf '; that progress cannot silently reverse.\n'
		printf '(def %%conformance-covered (lit (\n'
		sed 's/^/  (/; s/$/)/' "$W/real"
		printf ')))\n'
	} > "$FLOOR"
	echo "conformance-coverage: floor updated -- $ncov of $ntotal rows"
	exit 0
fi

fail=0
if [ -f "$FLOOR" ]; then
	awk '/^  \(/ { l=$0; gsub(/[()]/,"",l); $0=l; print $1 }' "$FLOOR" | sort -u > "$W/floor"
	comm -23 "$W/floor" "$W/real" > "$W/lost"
	if [ -s "$W/lost" ]; then
		echo "conformance-coverage: rows LOST coverage since the floor was set:"
		sed 's/^/    /' "$W/lost"
		echo "FAIL: the suite may only grow.  Re-add the cases, or justify the"
		echo "  removal and re-run with --update in the same commit."
		fail=1
	fi
fi

pct=$(( ncov * 100 / ntotal ))
echo "conformance-coverage: $ncov of $ntotal ISA rows defined ($pct%)."
if [ -s "$W/uncovered" ]; then
	echo "  not yet defined ($(wc -l < "$W/uncovered" | tr -d ' ') rows):"
	tr '\n' ' ' < "$W/uncovered" | fold -s -w 72 | sed 's/^/    /'
fi
[ "$fail" -eq 0 ] || exit 1
exit 0
