# 05-arithmetic.spec.sh -- Tests for arithmetic and bitwise operations
# Spec: Section 5 - Arithmetic

describe 'arithmetic basics'
  it 'adds two numbers' '(+ 1 2)' '3'
  it 'subtracts two numbers' '(- 10 3)' '7'
  it 'multiplies two numbers' '(* 4 5)' '20'
  it 'nests arithmetic' '(+ 1 (* 2 3))' '7'
  it 'handles negative results' '(- 3 10)' '-7'

describe 'variadic +'
  it 'adds two numbers' '(+ 1 2)' '3'
  it 'adds three numbers' '(+ 1 2 3)' '6'
  it 'adds many numbers' '(+ 1 2 3 4 5)' '15'
  it 'identity is 0' '(+)' '0'
  it 'single arg returns it' '(+ 5)' '5'

describe 'variadic -'
  it 'subtracts two numbers' '(- 10 3)' '7'
  it 'subtracts three numbers' '(- 10 3 2)' '5'
  it 'unary negates' '(- 5)' '-5'
  it 'no args returns 0' '(-)' '0'

describe 'variadic *'
  it 'multiplies two numbers' '(* 4 5)' '20'
  it 'multiplies three numbers' '(* 2 3 4)' '24'
  it 'identity is 1' '(*)' '1'
  it 'single arg returns it' '(* 7)' '7'

describe 'variadic /'
  it 'divides two numbers' '(/ 10 3)' '3'
  it 'divides evenly' '(/ 12 4)' '3'
  it 'handles negative dividend' '(/ -10 3)' '-3'
  it 'chains division' '(/ 100 5 2)' '10'

describe 'variadic %'
  it 'computes modulo' '(% 10 3)' '1'
  it 'returns zero for even division' '(% 12 4)' '0'
  it 'handles negative dividend' '(% -10 3)' '-1'
  it 'chains modulo' '(% 100 7 3)' '2'

describe '~ (bitwise NOT)'
  it 'inverts zero' '(~ 0)' '-1'
  it 'inverts one' '(~ 1)' '-2'
  it 'inverts negative' '(~ -1)' '0'
  it 'double invert is identity' '(~ (~ 42))' '42'

describe '& (bitwise AND)'
  it 'ands with zero' '(& 255 0)' '0'
  it 'ands with self' '(& 42 42)' '42'
  it 'masks low bits' '(& 255 15)' '15'
  it 'masks high nibble' '(& 170 240)' '160'

describe '| (bitwise OR)'
  it 'ors with zero' '(| 42 0)' '42'
  it 'ors complementary bits' '(| 170 85)' '255'
  it 'ors with self' '(| 42 42)' '42'

describe '^ (bitwise XOR)'
  it 'xors with zero' '(^ 42 0)' '42'
  it 'xors with self gives zero' '(^ 42 42)' '0'
  it 'xors complementary bits' '(^ 170 85)' '255'
  it 'double xor is identity' '(^ (^ 42 99) 99)' '42'

describe '<< (shift left)'
  it 'shifts by 0' '(<< 1 0)' '1'
  it 'shifts by 1' '(<< 1 1)' '2'
  it 'shifts by 4' '(<< 1 4)' '16'
  it 'shifts value' '(<< 5 3)' '40'

describe '>> (shift right)'
  it 'shifts by 0' '(>> 16 0)' '16'
  it 'shifts by 1' '(>> 16 1)' '8'
  it 'shifts by 4' '(>> 255 4)' '15'
  it 'shifts to zero' '(>> 1 1)' '0'
