# 21-lib-float.spec.sh -- Tests for floating-point type
# Spec: Section 21 - Float Library
LANG_LIB="$SCRIPT_DIR/../../lib/x.x"

describe 'float literals'
  it 'parses simple float' '3.14' '3.14'
  it 'parses integer-like float' '1.0' '1'
  it 'parses small float' '0.5' '0.5'
  it 'parses large float' '12345.6789' '12345.6789'
  it 'float? true for float' '(float? 3.14)' 't'
  it 'float? false for integer' '(null? (float? 42))' 't'
  it 'float? false for string' '(null? (float? "3.14"))' 't'

describe 'type convert handler'
  it 'convert int to float' '(convert 42 %float)' '42'
  it 'convert result is float' '(float? (convert 42 %float))' 't'
  it 'convert float to float is identity' '(def x 3.14) (eq? (convert x %float) x)' 't'
  it 'convert string to float' '(float? (convert "3.14" %float))' 't'
  it 'convert nil returns nil' '(null? (convert () %float))' 't'
  it 'convert negative int' '(convert -5 %float)' '-5'
  it 'convert zero' '(convert 0 %float)' '0'

describe 'float conversions'
  it 'exact->inexact converts int' '(exact->inexact 5)' '5'
  it 'exact->inexact result is float' '(float? (exact->inexact 5))' 't'
  it 'exact->inexact float identity' '(def x 3.14) (eq? (exact->inexact x) x)' 't'
  it 'inexact->exact truncates' '(inexact->exact 3.14)' '3'
  it 'inexact->exact rounds toward zero' '(inexact->exact 9.99)' '9'
  it 'string->float and back' '(float->string (string->float "2.718"))' '"2.718"'
  it 'int->float and back' '(float->int (int->float 42))' '42'

describe 'float arithmetic (f+ f- f* f/)'
  it 'f+ addition' '(f+ 1.5 2.5)' '4'
  it 'f- subtraction' '(f- 10.0 3.5)' '6.5'
  it 'f* multiplication' '(f* 3.0 4.0)' '12'
  it 'f/ division' '(f/ 10.0 4.0)' '2.5'
  it 'f/ non-integer result' '(f/ 1.0 3.0)' '0.333333333333333'

describe 'generic arithmetic with floats'
  it '+ two floats' '(+ 1.5 2.5)' '4'
  it '+ int and float' '(+ 1 2.5)' '3.5'
  it '+ float and int' '(+ 2.5 1)' '3.5'
  it '+ three with float' '(+ 1 2 3.0)' '6'
  it '- two floats' '(- 10.0 3.5)' '6.5'
  it '- negate float' '(- 3.14)' '-3.14'
  it '* two floats' '(* 3.0 4.0)' '12'
  it '* int and float' '(* 2 3.5)' '7'
  it '/ two floats' '(/ 10.0 4.0)' '2.5'
  it '/ int and float' '(/ 7 2.0)' '3.5'
  it '+ integers unchanged' '(+ 1 2 3)' '6'
  it '* integers unchanged' '(* 2 3 4)' '24'

describe 'float comparisons'
  it 'f< true' '(f< 1.5 2.5)' 't'
  it 'f< false' '(null? (f< 2.5 1.5))' 't'
  it 'f= true' '(f= 1.0 1.0)' 't'
  it 'f= false' '(null? (f= 1.0 2.0))' 't'

describe 'generic comparisons with floats'
  it '< with floats' '(< 1.5 2.5)' 't'
  it '> with floats' '(> 3.0 2.0)' 't'
  it '= with floats' '(= 1.0 1.0)' 't'
  it '<= with floats' '(<= 2.0 2.0)' 't'
  it '>= with floats' '(>= 3.0 2.0)' 't'
  it '< int and float' '(< 1 2.5)' 't'
  it '> float and int' '(> 3.5 2)' 't'
  it '= int and float' '(= 2 2.0)' 't'
  it '< integers still work' '(< 1 2)' 't'
  it '= integers still work' '(= 5 5)' 't'

describe 'math functions'
  it 'fsin of 0' '(fsin (exact->inexact 0))' '0'
  it 'fcos of 0' '(fcos (exact->inexact 0))' '1'
  it 'fsqrt of 4' '(fsqrt 4.0)' '2'
  it 'fsqrt of 2' '(fsqrt 2.0)' '1.4142135623731'
  it 'fabs positive' '(fabs 3.14)' '3.14'
  it 'fabs negative' '(fabs (- 3.14))' '3.14'
  it 'ffloor' '(ffloor 3.7)' '3'
  it 'fceil' '(fceil 3.2)' '4'
  it 'fround' '(fround 3.5)' '4'
  it 'fexp of 0' '(fexp (exact->inexact 0))' '1'
  it 'flog of 1' '(flog 1.0)' '0'
  it 'fpow 2^10' '(fpow 2.0 10.0)' '1024'

describe 'float constants'
  it 'pi is approximately 3.14159' '(> %pi 3.14)' 't'
  it 'pi is approximately 3.14159 upper' '(< %pi 3.15)' 't'
  it 'e is approximately 2.71828' '(> %e 2.71)' 't'
  it 'e is approximately 2.71828 upper' '(< %e 2.72)' 't'

describe 'float predicates'
  it 'number? true for integer' '(number? 42)' 't'
  it 'number? true for float' '(number? 3.14)' 't'
  it 'number? false for string' '(null? (number? "hello"))' 't'
  it 'integer? true for int' '(integer? 42)' 't'
  it 'integer? false for float' '(null? (integer? 3.14))' 't'
  it 'float? true for float' '(float? 3.14)' 't'
  it 'float? false for int' '(null? (float? 42))' 't'
  it 'inexact? true for float' '(inexact? 3.14)' 't'
  it 'inexact? false for int' '(null? (inexact? 42))' 't'

describe 'float in data structures'
  it 'float in list' '(list 1.5 2.5 3.5)' '(1.5 2.5 3.5)'
  it 'float in pair' '(pair 1.5 2.5)' '(1.5 . 2.5)'
  it 'float in variable' '(def x 3.14) x' '3.14'
  it 'map with floats' '(map (fn (x) (* x 2.0)) (list 1.0 2.0 3.0))' '(2 4 6)'
  it 'filter with floats' '(filter (fn (x) (> x 2.0)) (list 1.0 2.5 3.0 0.5))' '(2.5 3)'
  it 'fold with floats' '(fold + 0.0 (list 1.0 2.0 3.0))' '6'
  it 'float in vector' '(vector 1.5 2.5 3.5)' '#(1.5 2.5 3.5)'

describe 'float edge cases'
  it 'very small float' '(> 0.001 (exact->inexact 0))' 't'
  it 'negative float' '(- 3.14)' '-3.14'
  it 'float zero' '(f= 0.0 (exact->inexact 0))' 't'
  it 'mixed arithmetic chain' '(+ (* 2.0 3.0) (/ 10.0 5.0))' '8'
