#!/bin/sh
# amalgamate.sh -- flatten a boot entry's raw-include chain into one
# self-ordered stream on stdout (docs/boot-amalgam.md).
#
# Splice-only, line-oriented, top level only: each spliced file's forms
# land at STREAM top level, never wrapped in a grouping form -- the
# stream is parsed form-by-form as it evaluates, which preserves the
# tower's parse-before-eval ordering and keeps the (repl) launcher at
# the top level it requires.  Source text is copied verbatim (a reader
# round-trip would lose reader-sugar and formatting), so the interpreter
# sees byte-for-byte the same forms it sees under live includes, in the
# same effective order.
#
# Strict convention, machine-enforced here: a boot-closure raw include
# sits ALONE on its own line at column 0.  Any other root-relative
# include anywhere in the closure is a build error, not a silent skip.
# (Runtime modules never contain them at all -- tools/path-literals.sh.)
#
# Usage: sh tools/amalgamate.sh lib/xe.x > build/boot/xe.x

cd "$(dirname "$0")/.." || exit 1

[ -n "$1" ] || { echo "amalgamate: usage: amalgamate.sh <entry.x>" >&2; exit 1; }
[ -e "$1" ] || { echo "amalgamate: no such entry: $1" >&2; exit 1; }

awk -v entry="$1" '
function splice(path,  line, n) {
	if (path in seen) {
		printf "amalgamate: %s spliced twice\n", path > "/dev/stderr"
		bad = 1; exit 1
	}
	seen[path] = 1
	printf "; ---- begin %s ----\n", path
	n = 0
	while ((getline line < path) > 0) {
		n++
		if (line ~ /^[[:space:]]*;/) { print line; continue }
		if (line ~ /^\(include "(lib|tools|apps)\/[^"]*"\)[[:space:]]*(;.*)?$/) {
			sub(/^\(include "/, "", line)
			sub(/".*$/, "", line)
			if ((getline junk < line) < 0) {
				printf "amalgamate: %s:%d: cannot open %s\n", path, n, line > "/dev/stderr"
				bad = 1; exit 1
			}
			close(line)
			splice(line)
		} else if (line ~ /\((include|include-once|require-once)[[:space:]]+"(lib|tools|apps)\//) {
			printf "amalgamate: %s:%d: root-relative include not alone at column 0\n", path, n > "/dev/stderr"
			bad = 1; exit 1
		} else print line
	}
	close(path)
	printf "; ---- end %s ----\n", path
}
BEGIN {
	print "; GENERATED by tools/amalgamate.sh -- DO NOT EDIT (docs/boot-amalgam.md)"
	splice(entry)
	exit bad
}'
